// Generated by `npm run generate:smoke-bundle` from src/config/leadWhatsapp.js — do not edit; edit the source and regenerate.
/**
 * The message the desk's WhatsApp buttons open with (prompt 51).
 *
 * `settings.leads.whatsappTemplate` holds it, so the agency words it once —
 * with its own name read from Site settings, never the one this code was
 * written with. CommonJS, like `enums.js`, because the settings schema the mock
 * validates with reads the default too.
 */

/** Today's sentence, with the brand as a placeholder. */
const DEFAULT_WHATSAPP_TEMPLATE = 'Hello {name}, this is {brand} following up on your enquiry.';

/** What a template may say, and what each becomes. */
const WHATSAPP_PLACEHOLDERS = [
  { key: 'name', label: 'the lead’s name' },
  { key: 'property', label: 'the listing they asked about' },
  { key: 'agent', label: 'the colleague the lead is with' },
  { key: 'link', label: 'the listing’s address on the site' },
  { key: 'brand', label: 'the site name from Site settings' },
];

const PLACEHOLDER = /\{(name|property|agent|link|brand)\}/g;

/**
 * A template with its placeholders filled in.
 *
 * A placeholder with nothing behind it — no listing, no colleague — is left out
 * with the space before it, and the spaces it leaves before a comma or a full
 * stop are closed: "Hello {name}, about {property}." for a lead with no listing
 * reads "Hello Asha, about." rather than "Hello Asha, about {property}.".
 *
 * @param {string} template
 * @param {{name?: string, property?: string, agent?: string, link?: string, brand?: string}} values
 * @returns {string}
 */
function fillWhatsappTemplate(template, values = {}) {
  const text =
    typeof template === 'string' && template.trim() ? template : DEFAULT_WHATSAPP_TEMPLATE;
  return text
    .replace(PLACEHOLDER, (_match, key) => String(values[key] ?? '').trim())
    .replace(/[ \t]+([,.!?;:])/g, '$1')
    .replace(/[ \t]{2,}/g, ' ')
    .trim();
}

module.exports = { DEFAULT_WHATSAPP_TEMPLATE, WHATSAPP_PLACEHOLDERS, fillWhatsappTemplate };
