// Generated by `npm run generate:smoke-bundle` from src/services/schemas/auth.js — do not edit; edit the source and regenerate.
/**
 * Authentication write schemas (00_MASTER_CONTEXT.md §5.4).
 */

const login = {
  email: { type: 'email', required: true },
  password: { type: 'string', required: true, min: 6, maxLength: 100 },
};

// `avatarUrl`, like every `url`, is at most 500 characters — the width of its
// column (`./limits.js`, QA-65).
const profile = {
  name: { type: 'string', required: true, min: 2, maxLength: 80 },
  phone: { type: 'phone', nullable: true, default: null },
  avatarUrl: { type: 'url', nullable: true, default: null },
};

const password = {
  currentPassword: { type: 'string', required: true, maxLength: 100 },
  newPassword: { type: 'string', required: true, min: 8, maxLength: 100 },
};

/**
 * A password holds a letter and a digit as well as its eight characters: "not
 * eight letters or eight digits" (§5.4). One rule for every place a password is
 * set — the owner changing their own, an administrator creating an account or
 * resetting one — and QA-64 found it kept by the first alone: the Users screen
 * created and reset accounts with `aaaaaaaa` and `12345678`.
 */
const PASSWORD_PATTERN = /^(?=.*[A-Za-z])(?=.*\d)/;

/** The API's sentence for a password that breaks the rule, naming its field. */
const passwordMessage = (field = 'password') =>
  `The ${field} must contain at least one letter and one digit.`;

module.exports = { login, profile, password, PASSWORD_PATTERN, passwordMessage };
