// Generated by `npm run generate:smoke-bundle` from src/services/schemas/headerMenu.js — do not edit; edit the source and regenerate.
/**
 * Header menu write schemas (00_MASTER_CONTEXT.md §6.10, §6.13; QA-56).
 *
 * The header was a list in `config/navigation.js`, and a page could join one of
 * three of its menus — Buyer assistance, Company, Insights — and nothing else.
 * Its menus are records now, left to right by `order`:
 *
 *   - `name` is the label the bar shows, `slug` the key a page holds in
 *     `headerMenu` (derived from the name, and kept once the menu exists);
 *   - `href` is where the label itself goes — a path on this site or a full
 *     address; empty, the label opens the menu's first link;
 *   - `source` says what the panel is built from: `custom` menus are the pages
 *     placed in them plus the links typed into them; `buy`, `rent` and
 *     `commercial` are the site's generated mega menus, which take pages and
 *     links on top of their own columns;
 *   - `submenus[]` are the panel's groups — a page or a link names one by its
 *     slug, and lands in the menu's own list when it names none;
 *   - `links[]` are destinations that are not pages: a filtered listing, a
 *     section of the site, another site.
 *
 * A menu with nothing in its panel is a plain link when it has an `href`
 * (Plots, Contact) and is left out of the bar when it has neither (§7).
 */

const { HEADER_MENU_SOURCES } = require('../../config/enums');

/** A slug of one or more lowercase words joined by hyphens. */
const SLUG_PATTERN = '^[a-z0-9]+(?:-[a-z0-9]+)*$';

/**
 * Where a menu or a link goes: a path on this site (`/buy?maxPrice=5000000`)
 * or a full `http(s)` address.
 */
const HREF_PATTERN = '^(/(?!/)|https?://)';

/** A menu's own slug — a `slug` like any record's, derived when sent empty (§5.9). */
const MENU_SLUG_MAX_LENGTH = 60;

const submenu = {
  type: 'object',
  shape: {
    slug: { type: 'string', required: true, maxLength: 75, pattern: SLUG_PATTERN },
    name: { type: 'string', required: true, min: 1, maxLength: 60 },
  },
};

const link = {
  type: 'object',
  shape: {
    label: { type: 'string', required: true, min: 1, maxLength: 80 },
    href: { type: 'string', required: true, maxLength: 500, pattern: HREF_PATTERN },
    // A `submenus[].slug` of the same menu; the menu resource checks it.
    submenu: { type: 'string', nullable: true, maxLength: 75, default: null },
    order: { type: 'int', min: 0, max: 100000, default: 0 },
    newTab: { type: 'bool', default: false },
  },
};

const create = {
  name: { type: 'string', required: true, min: 1, maxLength: 40 },
  slug: { type: 'slug', maxLength: MENU_SLUG_MAX_LENGTH, default: '' },
  href: {
    type: 'string',
    nullable: true,
    maxLength: 500,
    pattern: HREF_PATTERN,
    default: null,
  },
  source: {
    type: 'enum',
    enum: HEADER_MENU_SOURCES.values,
    required: true,
    default: 'custom',
  },
  submenus: { type: 'array', items: submenu, max: 12, default: [] },
  links: { type: 'array', items: link, max: 40, default: [] },
  isActive: { type: 'bool', default: true },
  order: { type: 'int', min: 0, max: 100000, default: 0 },
};

/** Every key optional, one level deep — the `PATCH` variant. */
const patch = Object.fromEntries(
  Object.entries(create).map(([name, descriptor]) => {
    const { required: _required, ...rest } = descriptor;
    return [name, rest];
  })
);

module.exports = {
  create,
  update: create,
  patch,
  HREF_PATTERN,
  SLUG_PATTERN,
};
