// Generated by `npm run generate:smoke-bundle` from src/services/schemas/newsletter.js — do not edit; edit the source and regenerate.
/**
 * Newsletter subscription (00_MASTER_CONTEXT.md §5.14, §6.14).
 * A duplicate e-mail answers 200 `{ data: null, message: 'Already subscribed' }`
 * rather than 409 — subscribing twice is not an error for the visitor.
 */

const { NEWSLETTER_STATUS, SITE_LEAD_SOURCES } = require('../../config/enums');

const subscribe = {
  email: { type: 'email', required: true },
  name: { type: 'string', nullable: true, maxLength: 80, default: null },
  source: { type: 'enum', enum: SITE_LEAD_SOURCES, default: 'newsletter' },
  // Honeypot (§5.11).
  website: { type: 'string', nullable: true, maxLength: 200, default: null },
};

/**
 * `PATCH /admin/newsletter-subscribers/:id` — the one thing about a subscriber
 * an editor changes: somebody who asked, by e-mail or on the phone, to stop
 * receiving it (prompt 51).
 */
const status = {
  status: { type: 'enum', enum: NEWSLETTER_STATUS.values, required: true },
};

module.exports = { subscribe, status };
