// Generated by `npm run generate:smoke-bundle` from src/services/schemas/seo.js — do not edit; edit the source and regenerate.
/**
 * The `seo` sub-schema (00_MASTER_CONTEXT.md §9.6) — identical on every
 * entity that owns a public URL: properties, articles, pages, localities,
 * developers, property types, article categories and authors.
 *
 * CommonJS (D36b): shared by the React forms, the mock validator and the
 * backend-guidelines generator.
 *
 * Field descriptor mini-language (see mock-server/schemas/README.md):
 *   { type, required, nullable, enum, min, max, maxLength, items, shape, default }
 */

const {
  REDIRECT_CODES,
  SEO_SCHEMA_TYPES,
  SEO_SCORE_BANDS,
  SEO_TEST_STATUS,
  SITEMAP_CHANGEFREQ,
} = require('../../config/enums');

/** One analyser result row: `{ id, status, message }`. */
const seoAnalysisItem = {
  type: 'object',
  shape: {
    id: { type: 'string', required: true, maxLength: 80 },
    status: { type: 'enum', enum: SEO_TEST_STATUS.values, required: true },
    message: { type: 'string', required: true, maxLength: 500 },
  },
};

/** `seo.robots` — the directives rendered into the robots meta tag. */
const seoRobots = {
  type: 'object',
  shape: {
    index: { type: 'bool', default: true },
    follow: { type: 'bool', default: true },
    noarchive: { type: 'bool', default: false },
    nosnippet: { type: 'bool', default: false },
    noimageindex: { type: 'bool', default: false },
    maxSnippet: { type: 'int', nullable: true, min: -1, default: null },
    maxImagePreview: {
      type: 'enum',
      enum: ['none', 'standard', 'large'],
      nullable: true,
      default: 'large',
    },
    maxVideoPreview: { type: 'int', nullable: true, min: -1, default: null },
  },
  default: {
    index: true,
    follow: true,
    noarchive: false,
    nosnippet: false,
    noimageindex: false,
    maxSnippet: null,
    maxImagePreview: 'large',
    maxVideoPreview: null,
  },
};

const seo = {
  type: 'object',
  shape: {
    focusKeyword: { type: 'string', maxLength: 120, default: '' },
    secondaryKeywords: {
      type: 'array',
      items: { type: 'string', maxLength: 120 },
      max: 10,
      default: [],
    },
    title: { type: 'string', maxLength: 200, default: '' },
    description: { type: 'string', maxLength: 320, default: '' },
    slug: { type: 'slug', maxLength: 75, default: '' },
    canonicalUrl: { type: 'url', nullable: true, default: null },
    robots: seoRobots,
    og: {
      type: 'object',
      shape: {
        title: { type: 'string', nullable: true, maxLength: 200, default: null },
        description: { type: 'string', nullable: true, maxLength: 320, default: null },
        imageUrl: { type: 'url', nullable: true, default: null },
      },
      default: { title: null, description: null, imageUrl: null },
    },
    twitter: {
      type: 'object',
      shape: {
        card: {
          type: 'enum',
          enum: ['summary', 'summary_large_image'],
          default: 'summary_large_image',
        },
        title: { type: 'string', nullable: true, maxLength: 200, default: null },
        description: { type: 'string', nullable: true, maxLength: 320, default: null },
        imageUrl: { type: 'url', nullable: true, default: null },
      },
      default: {
        card: 'summary_large_image',
        title: null,
        description: null,
        imageUrl: null,
      },
    },
    breadcrumbTitle: { type: 'string', nullable: true, maxLength: 120, default: null },
    schema: {
      type: 'object',
      shape: {
        type: { type: 'enum', enum: SEO_SCHEMA_TYPES.values, default: 'auto' },
        custom: { type: 'string', default: '' },
        disabledAutoTypes: { type: 'array', items: { type: 'string' }, default: [] },
      },
      default: { type: 'auto', custom: '', disabledAutoTypes: [] },
    },
    sitemap: {
      type: 'object',
      shape: {
        include: { type: 'bool', default: true },
        priority: { type: 'number', nullable: true, min: 0, max: 1, default: null },
        changefreq: {
          type: 'enum',
          enum: SITEMAP_CHANGEFREQ.values,
          nullable: true,
          default: null,
        },
      },
      default: { include: true, priority: null, changefreq: null },
    },
    redirect: {
      type: 'object',
      shape: {
        enabled: { type: 'bool', default: false },
        toPath: { type: 'string', maxLength: 500, default: '' },
        statusCode: { type: 'enum', enum: REDIRECT_CODES.values, default: 301 },
      },
      default: { enabled: false, toPath: '', statusCode: 301 },
    },
    score: { type: 'int', nullable: true, min: 0, max: 100, default: null },
    scoreBand: { type: 'enum', enum: SEO_SCORE_BANDS.values, default: 'none' },
    testsPassed: { type: 'int', min: 0, default: 0 },
    testsTotal: { type: 'int', min: 0, default: 0 },
    analysis: {
      type: 'object',
      shape: {
        basic: { type: 'array', items: seoAnalysisItem, default: [] },
        additional: { type: 'array', items: seoAnalysisItem, default: [] },
        titleReadability: { type: 'array', items: seoAnalysisItem, default: [] },
        contentReadability: { type: 'array', items: seoAnalysisItem, default: [] },
      },
      default: { basic: [], additional: [], titleReadability: [], contentReadability: [] },
    },
    lastAnalyzedAt: { type: 'datetime', nullable: true, default: null },
  },
};

/**
 * `POST /not-found` — the site's 404 page reporting the address it was reached
 * at, and where from (prompt 51). The path must start with `/`; the API
 * ignores the admin, the API and static files.
 */
const notFoundReport = {
  path: { type: 'string', required: true, maxLength: 500 },
  referrer: { type: 'string', nullable: true, maxLength: 500, default: null },
};

module.exports = { seo, seoRobots, seoAnalysisItem, notFoundReport };
