import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Icon } from '@iconify/react';
import { useNavigate, useParams } from 'react-router-dom';

import ApiError from '../../../services/apiError';
// The master-data form before the block editor, out of alphabetical order: the
// two reach the same admin kit, and the kit's stylesheets have to arrive in the
// order every master-data screen gives them — this page shares a chunk with
// them, and two orders for one chunk is a mini-css-extract "Conflicting
// order", which `build:ci` refuses.
import { FormFieldControl } from '../../../components/admin/MasterDataForm';
import focusFirstError from '../../../components/admin/focusFirstError';
import BlockEditor from '../../../components/cms/BlockEditor/BlockEditor';
import PATHS, { RESERVED_PATH_PREFIXES, isReservedPath } from '../../../routes/paths';
import openInNewTab from '../../../utils/openInNewTab';
import pageService from '../../../services/pageService';
import redirectService from '../../../services/redirectService';
import useApi from '../../../hooks/useApi';
import useForm from '../../../hooks/useForm';
import useUnsavedChanges from '../../../hooks/useUnsavedChanges';
import { useAdminAuth } from '../../../contexts/AdminAuthContext';
import { useNavigationGuard } from '../../../contexts/NavigationGuardContext';
// The kit is imported file by file, in the order `MasterDataPage` reaches for
// the same components: the barrel's own order disagrees with it, and webpack
// then cannot give the extracted CSS one order across the admin chunks.
import FormSection, { FormColumn } from '../../../components/admin/FormSection';
import SeoPanel from '../../../components/seo/SeoPanel';
import PageHeader from '../../../components/admin/PageHeader';
import SlugField from '../../../components/admin/SlugField';
import {
  Button,
  ErrorState,
  RadioGroup,
  SelectField,
  Skeleton,
  SwitchField,
  TextField,
} from '../../../components/ui';
import { FOOTER_COLUMNS, LEAD_SOURCES, PAGE_STATUS, PAGE_TEMPLATES } from '../../../config/enums';
import {
  SYSTEM_TEMPLATE,
  homeRedirectRefusal,
  isHomePage,
  isSystemPage,
  slugRefusal,
  systemPageOf,
  unpublishRefusal,
} from '../../../config/pages';
import { MANAGED_AT, useHeaderMenus } from './pagesAdmin';
import {
  PAGE_ORDER_MAX,
  PAGE_TITLE_MAX_LENGTH,
  PAGE_TITLE_MIN_LENGTH,
} from '../../../services/schemas/page';
import { validateBlockData } from '../../../components/cms/BlockEditor/blockSchemas';
import {
  applySeoSideEffects,
  redirectWarning,
  validateSeoBranch,
} from '../../../components/seo/seoSideEffects';
import { clearCache as clearRedirectCache } from '../../../components/common/RedirectHandler';
import {
  createSeo,
  toSeoPaths,
  toSeoPayload,
  withSeoDefaults,
} from '../../../components/seo/seoValues';
import { resetNavPagesCache } from '../../../hooks/useNavPages';
import { schemas } from '../../../services/schemas';
import { slugifyPath } from '../../../utils/slug';
import { useToast } from '../../../components/common/ToastProvider';
import { FORMS } from '../../../config/adminCopy';

import styles from './PageFormPage.module.css';

/**
 * Admin → Pages → add / edit (`/admin/pages/add|edit/:id`).
 *
 * A page is a title, a URL, where it appears in the menus, and a stack of
 * blocks. The first three are an ordinary form; the fourth is `BlockEditor`,
 * which is why this is a screen rather than a dialog.
 *
 * **The URL is a path.** Alone among the site's records, a page's slug may
 * carry separators — `buyer-assistance/home-loan` is one slug, and the public
 * route serves the page at exactly that path (§6.10). `SlugField` is put in
 * `path` mode, which slugifies each segment and leaves the `/` alone, and a
 * slug whose first segment belongs to a static route is refused here rather
 * than silently shadowed on the site (D11). Moving a live page offers a 301
 * from the address it leaves (QA-56).
 *
 * **Some pages are protected** (`config/pages.js`, QA-56): their address is
 * fixed and they are never deleted. A **built-in** page — Buy, Localities,
 * Articles… — is generated by the site: its name and its place in the menus
 * are edited here, its content and its head are not.
 *
 * **Errors reach the block that caused them.** The API keys a 422 as
 * `blocks.3.data.items.0.title`; the same key is what `validateBlockData`
 * produces before a save is even attempted, so both end up on the same box,
 * and the card above it wears a badge saying how many of them it holds.
 */

/** A new page, at the values its controls read as empty. */
const BLANK = {
  title: '',
  slug: '',
  template: 'standard',
  status: 'draft',
  heroImageUrl: '',
  blocks: [],
  leadSource: '',
  order: 0,
  showInHeader: false,
  headerMenu: '',
  headerSubmenu: '',
  showInFooter: false,
  footerColumn: '',
  seo: createSeo(),
  updatedAt: null,
};

/** The record, reduced to what this form edits. */
const toFormValues = (record) => ({
  title: record.title ?? '',
  slug: record.slug ?? '',
  template: record.template ?? 'standard',
  status: record.status ?? 'draft',
  heroImageUrl: record.heroImageUrl ?? '',
  blocks: (Array.isArray(record.blocks) ? record.blocks : []).map((block, index) => ({
    id: block.id,
    type: block.type,
    order: block.order ?? index + 1,
    data: block.data ?? {},
  })),
  leadSource: record.leadSource ?? '',
  order: record.order ?? 0,
  showInHeader: Boolean(record.showInHeader),
  headerMenu: record.headerMenu ?? '',
  headerSubmenu: record.headerSubmenu ?? '',
  showInFooter: Boolean(record.showInFooter),
  footerColumn: record.footerColumn ?? '',
  // Every field of §9.6 present, whatever the record was saved with.
  seo: withSeoDefaults(record.seo),
  // Read-only, never sent back: the SEO panel prints it as "last modified".
  updatedAt: record.updatedAt ?? null,
});

const trimmed = (value) => (typeof value === 'string' ? value.trim() : '');

/**
 * What the messages call a field whose key is not a word (`useForm`'s
 * `labels`): the API and the schema say "The headerMenu field is required.".
 */
const FIELD_LABELS = {
  headerMenu: 'header menu',
  headerSubmenu: 'submenu',
  footerColumn: 'footer column',
  leadSource: 'default lead source',
  heroImageUrl: 'hero image',
};

/**
 * What the SEO analysers call a field, and where it is on this screen.
 *
 * A page's body is its blocks, so "the body never uses the focus keyword"
 * scrolls to the block editor; everything else the engine can name about a page
 * is either the URL or a field of the panel itself.
 */
const FIELD_TARGET = { content: 'page-content', slug: 'page-slug', images: 'page-content' };

/** Brings the block a hint names into view, and focuses the first control in it. */
function focusField(path) {
  const element = document.getElementById(FIELD_TARGET[path] ?? '');
  if (!element) return;

  const control = element.querySelector('input, textarea, select, [contenteditable="true"]');
  control?.focus?.();
  element.scrollIntoView?.({ block: 'center', behavior: 'smooth' });
}

/**
 * `SlugField`'s availability check, in the shape it hands over.
 *
 * Module level so its identity is stable: the field debounces on it, and a new
 * arrow on every render would ask the API after every keystroke of the title.
 */
const checkPageSlug = (slug, { excludeId, signal } = {}) =>
  pageService.checkSlug({ slug, excludeId }, { signal });

/**
 * The two blocks the home page draws — one Features ("Why choose us") and one
 * Steps ("How it works") — and only while there is not one already: anything
 * else added to the home record was saved and never appeared (prompt 51).
 */
const HOME_BLOCK_TYPES = ['features', 'steps'];
const HOME_BLOCKS_NOTE =
  'The home page shows one Features block (“Why choose us”) and one Steps block (“How it works”); the rest of it is built from Site settings and the listings.';

/** The home block types not on the page yet. Exported for the unit test. */
export const homeBlockTypes = (blocks = []) =>
  HOME_BLOCK_TYPES.filter(
    (type) => !(Array.isArray(blocks) ? blocks : []).some((block) => block?.type === type)
  );

/** The templates an editor may choose — "Built-in" is the site's own (QA-56). */
const WRITTEN_TEMPLATES = PAGE_TEMPLATES.options.filter(
  (option) => option.value !== SYSTEM_TEMPLATE
);

/**
 * The blocks as the API stores them (§5.5, §6.10).
 *
 * A block the editor added carries a `tmp-…` id, which is not the integer the
 * schema asks for. It is swapped for the next free number in the page's own
 * array — the server renumbers `order` anyway and keeps ids it is given, so the
 * numbering only has to be unique within the page.
 *
 * Exported for the unit test.
 *
 * @param {Array<object>} blocks
 * @returns {Array<object>}
 */
export function toBlockPayload(blocks) {
  const list = Array.isArray(blocks) ? blocks : [];
  let highest = list.reduce(
    (max, block) => (Number.isInteger(block?.id) ? Math.max(max, block.id) : max),
    0
  );

  return list.map((block, index) => ({
    id: Number.isInteger(block.id) ? block.id : (highest += 1),
    type: block.type,
    order: index + 1,
    data: block.data ?? {},
  }));
}

export default function PageFormPage() {
  const { id } = useParams();
  const isEdit = Boolean(id);
  const navigate = useNavigate();
  const toast = useToast();
  // The 301 a moved page leaves behind is a row of SEO → Redirects.
  const canRedirect = useAdminAuth().can('seo', 'edit');

  const {
    data: record,
    loading,
    error,
    refetch,
  } = useApi((signal) => pageService.adminGet(id, { signal }), [id], { enabled: isEdit });

  const {
    menus,
    loading: menusLoading,
    error: menusError,
    refetch: refetchMenus,
  } = useHeaderMenus();

  // The record as last saved: the load, then the answer to each save. A save
  // used to read the record again, which put the whole form behind its loading
  // skeleton — the scroll went back to the top and every open block closed
  // (QA-56). The API's answer is the record; it is used as it is.
  const [stored, setStored] = useState(null);

  const system = isSystemPage(stored);
  const home = isHomePage(stored);
  const lockedSlug = stored ? slugRefusal(stored) : null;
  const builtIn = system ? systemPageOf(stored.slug) : null;

  const [redirect, setRedirect] = useState(null);
  const [previewing, setPreviewing] = useState(false);
  // "Publish" is a status change *and* a save. `setField` lands one render
  // later, so the save waits for the render that commits it rather than
  // building its payload from the status still on screen — and remembers the
  // status it came from, to put it back if the save is refused.
  const [publishing, setPublishing] = useState(null);
  // Moving a live page's URL: send visitors from the old address (QA-56).
  const [redirectOld, setRedirectOld] = useState(true);
  // A refused save: the block editor opens the cards holding a message, then
  // the cursor goes to the first one (prompt 51).
  const [revealErrors, setRevealErrors] = useState(0);
  const formRef = useRef(null);

  const toPayload = useCallback(
    (values) => {
      const slug = lockedSlug && stored ? stored.slug : slugifyPath(values.slug ?? '');
      const inHeader = Boolean(values.showInHeader) && Boolean(values.headerMenu);
      return {
        title: trimmed(values.title),
        slug,
        template: system ? SYSTEM_TEMPLATE : values.template || 'standard',
        status: system ? 'published' : values.status || 'draft',
        heroImageUrl: system ? null : values.heroImageUrl || null,
        // A built-in page's content is the site's own; it carries no blocks.
        blocks: system ? [] : toBlockPayload(values.blocks),
        leadSource: system ? null : values.leadSource || null,
        order: Number(values.order) || 0,
        showInHeader: Boolean(values.showInHeader),
        headerMenu: values.showInHeader ? values.headerMenu || null : null,
        headerSubmenu: inHeader ? values.headerSubmenu || null : null,
        showInFooter: Boolean(values.showInFooter),
        footerColumn: values.showInFooter ? values.footerColumn || null : null,
        // D34: one URL — `seo.slug` always mirrors the page's own.
        seo: toSeoPayload(values.seo, slug),
      };
    },
    [lockedSlug, stored, system]
  );

  /**
   * The rules the descriptor cannot express: a title the API will take, a URL
   * nothing else already answers, and a menu placement that names its menu.
   */
  const extraValidation = useCallback(
    (values) => {
      const found = {};
      const title = trimmed(values.title);
      const slug = slugifyPath(values.slug ?? '');

      // The API's own bounds (§6.10): the form asked for 3–120 characters
      // while the box took 150 and the API 2–150, so a copy of a long title
      // could not be saved here at all (QA-56).
      if (title.length > 0 && title.length < PAGE_TITLE_MIN_LENGTH) {
        found.title = `The title must be at least ${PAGE_TITLE_MIN_LENGTH} characters.`;
      }
      if (title.length > PAGE_TITLE_MAX_LENGTH) {
        found.title = `The title may not be longer than ${PAGE_TITLE_MAX_LENGTH} characters.`;
      }

      if (!lockedSlug) {
        if (!slug) found.slug = 'The URL is required.';
        // A slug under a reserved prefix would be shadowed by the static route
        // that owns it, so the page would exist and never be reachable (D11).
        // An existing page already living there — the seeded awareness page —
        // is left alone: its route is spelled out, so it is not shadowed.
        else if (isReservedPath(slug) && slug !== stored?.slug) {
          found.slug = `Reserved path — “${slug.split('/')[0]}” belongs to the site’s own pages.`;
        }
      }

      if (values.showInHeader && !values.headerMenu) {
        found.headerMenu = 'Choose which header menu this page belongs to.';
      }
      if (values.showInFooter && !values.footerColumn) {
        found.footerColumn = 'Choose which footer column this page belongs to.';
      }

      // Every block, against its own schema, keyed exactly as a 422 would be.
      if (!system) {
        (Array.isArray(values.blocks) ? values.blocks : []).forEach((block, index) => {
          const messages = validateBlockData(block.type, block.data ?? {});
          for (const [key, message] of Object.entries(messages)) {
            found[`blocks.${index}.data.${key}`] = message;
          }
        });

        // The SEO panel's own blockers: JSON-LD that would invalidate the
        // page's script tag, a redirect with nowhere to send anybody, and an
        // address past 500 characters.
        Object.assign(found, validateSeoBranch(values.seo));

        // The home page lives at `/`: redirecting it sends the whole site away.
        if (home && values.seo?.redirect?.enabled === true) {
          found['seo.redirect.enabled'] = homeRedirectRefusal();
        }
      }

      return found;
    },
    [home, lockedSlug, stored?.slug, system]
  );

  const form = useForm({
    initialValues: BLANK,
    schema: isEdit ? schemas['page.update'] : schemas['page.create'],
    validate: extraValidation,
    normalize: toPayload,
    labels: FIELD_LABELS,
    onSubmit: async (payload) => {
      try {
        const envelope = isEdit
          ? await pageService.update(id, payload)
          : await pageService.create(payload);
        return envelope?.data ?? null;
      } catch (thrown) {
        throw await withSlugSuggestion(thrown, payload.slug, id);
      }
    },
  });

  const { reset, values, setField, errors } = form;

  useEffect(() => {
    if (!record) return;
    setStored(record);
    reset(toFormValues(record));
  }, [record, reset]);

  useUnsavedChanges(form.dirty);

  // A menu added in another tab (the placement's "Manage" link opens one) is
  // offered here as soon as the editor comes back to this one.
  useEffect(() => {
    const onVisible = () => {
      if (document.visibilityState === 'visible') refetchMenus();
    };
    document.addEventListener('visibilitychange', onVisible);
    return () => document.removeEventListener('visibilitychange', onVisible);
  }, [refetchMenus]);

  // Leaving after a save waits for the guard to let go, twice over — the same
  // dance `LocalityFormPage` documents: a saved form is clean, but the provider
  // and `useBlocker` each learn that one render later.
  const { isBlocking } = useNavigationGuard();
  useEffect(() => {
    if (!redirect || isBlocking) return undefined;
    const timer = setTimeout(() => navigate(redirect.to, { replace: redirect.replace }), 0);
    return () => clearTimeout(timer);
  }, [redirect, isBlocking, navigate]);

  /**
   * `{ [blockId]: { field: message } }` — the flat error map, regrouped so that
   * each card can badge itself and each box inside it can find its own message.
   */
  const blockErrors = useMemo(() => {
    const grouped = {};
    const blocks = Array.isArray(values.blocks) ? values.blocks : [];

    for (const [key, message] of Object.entries(errors)) {
      // A message about the block itself — an unknown `type` the API refuses —
      // lands on its card as `type`; one inside it keeps its own field.
      const match =
        /^blocks\.(\d+)\.data\.(.+)$/.exec(key) ?? /^blocks\.(\d+)\.(type|id|order)$/.exec(key);
      if (!match) continue;
      const block = blocks[Number(match[1])];
      if (!block) continue;
      const blockId = String(block.id);
      const field = key.includes('.data.') ? match[2] : 'type';
      grouped[blockId] = { ...grouped[blockId], [field]: message };
    }

    return grouped;
  }, [errors, values.blocks]);

  /** The address a live page is leaving, when its URL has been changed. */
  const liveSlug = stored?.status === 'published' && !lockedSlug ? stored.slug : null;
  const typedSlug = slugifyPath(values.slug ?? '');
  const slugMoved = Boolean(isEdit && liveSlug && typedSlug && typedSlug !== liveSlug);
  const redirectsMove = slugMoved && canRedirect && redirectOld;

  /**
   * Sends visitors from the address a page left to the one it moved to — a
   * 301, the rule the SEO guide asks for whenever a slug changes — and retires
   * a rule that pointed the new address somewhere else, which would now loop.
   */
  const redirectMovedPage = async (fromSlug, saved) => {
    const fromPath = PATHS.page(fromSlug);
    const toPath = PATHS.page(saved.slug);
    try {
      await redirectService.deactivateByFromPath(toPath);
      await redirectService.upsertByFromPath({
        fromPath,
        toPath,
        statusCode: 301,
        note: `“${saved.title}” moved (Admin → Pages).`,
      });
      // This browser's copy of the table is ten minutes old at most; the new
      // rule is for this editor to try at once too.
      clearRedirectCache();
      toast.info(`${fromPath} now redirects to ${toPath}.`);
    } catch (thrown) {
      toast.error(
        `The page was saved, but ${fromPath} could not be redirected: ${
          thrown?.message || 'the redirect was refused'
        }. Add it under SEO → Redirects.`
      );
    }
  };

  /**
   * Saves the page.
   *
   * @param {{force?: boolean}} [options] `force` saves an unchanged form — a
   *   status change that has just been applied is a change
   * @returns {Promise<object|null|false>} the stored record; `false` when the
   *   save was refused
   */
  const save = async ({ force = false } = {}) => {
    // A save the rules refuse says so, opens the block that holds the problem
    // and puts the cursor on it: silent, with the message inside a collapsed
    // card, Save and Publish looked dead (prompt 51).
    const refuse = () => {
      toast.error(FORMS.fixFields);
      setRevealErrors((count) => count + 1);
      return false;
    };

    // Nothing has changed since the last save: say so rather than write the
    // same record again — a rewrite moved it to the top of the list sorted by
    // "Updated" and changed the date its sitemap entry reports (QA-56).
    if (isEdit && stored && !form.dirty && !force) {
      if (!form.validateAll()) return refuse();
      toast.info('No changes to save.');
      return stored;
    }

    if (!form.validateAll()) return refuse();

    const leaving = redirectsMove ? liveSlug : null;
    const saved = await form.submit();
    if (!saved) {
      // A 422 from the API is already toasted; its messages still need finding.
      setRevealErrors((count) => count + 1);
      return false;
    }

    setStored(saved);
    reset(toFormValues(saved));

    // The header and footer menus are built from the published pages and are
    // cached for the page load (D93).
    resetNavPagesCache();
    // The redirect this page's `seo` asks for, against the slug the API
    // answered with — a new page has none until now (§9.6).
    const effects = await applySeoSideEffects('page', saved);
    if (leaving && saved.slug !== leaving) await redirectMovedPage(leaving, saved);

    if (!effects.ok) {
      toast.warning(redirectWarning(effects.error));
    } else {
      toast.success(
        isEdit
          ? saved.status === 'published'
            ? 'Page saved. It is live.'
            : 'Page saved.'
          : 'Page created.'
      );
    }

    // A created page moves to its own URL, replacing the add route so Back
    // does not offer to create it a second time.
    if (!isEdit && saved.id) {
      setRedirect({ to: PATHS.adminPageEdit(saved.id), replace: true });
    }
    return saved;
  };

  const saveRef = useRef(save);
  saveRef.current = save;

  // After the render that opened the blocks holding a message.
  useEffect(() => {
    if (revealErrors === 0) return;
    focusFirstError(formRef.current);
  }, [revealErrors]);

  // The second half of "Publish": the status is now `published` in state, so
  // the save builds the payload that says so. A refusal puts the status back:
  // left on "Published", the radio said so over a draft, "Publish" had gone,
  // and the plain Save that followed a fix published the page (QA-56).
  useEffect(() => {
    if (!publishing || values.status !== 'published') return;
    const from = publishing.from;
    setPublishing(null);
    Promise.resolve(saveRef.current({ force: true })).then((saved) => {
      if (!saved) setField('status', from);
    });
  }, [publishing, setField, values.status]);

  const publish = () => {
    setPublishing({ from: values.status });
    setField('status', 'published');
  };

  // Ctrl/Cmd+S saves rather than offering to save the HTML of the page. Every
  // button that saves is disabled while a save is in flight; the keyboard is
  // not, so the shortcut refuses a second one itself, and a held key's
  // auto-repeat. Inside a dialog — a block being deleted, a link being
  // edited — the keys belong to the dialog.
  const busyRef = useRef(false);
  busyRef.current = form.submitting || previewing || publishing !== null;
  useEffect(() => {
    const onKeyDown = (event) => {
      if (event.key !== 's' && event.key !== 'S') return;
      if (!event.ctrlKey && !event.metaKey) return;
      if (event.altKey || event.shiftKey) return;
      event.preventDefault();
      if (event.repeat || busyRef.current) return;
      if (event.target?.closest?.('[role="dialog"], [aria-modal="true"]')) return;
      saveRef.current();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, []);

  /**
   * Save when there is something to save, then open the page in a new tab
   * behind a 24-hour token (D28).
   *
   * An unchanged page is not written again (QA-56). Only a tab the browser
   * genuinely refused becomes a navigation in this one (`openInNewTab`); a new
   * page keeps its move to its own edit URL instead, and is told where the
   * preview is.
   */
  const saveAndPreview = async () => {
    setPreviewing(true);
    try {
      let target = stored;
      if (!isEdit || form.dirty) {
        const saved = await save();
        if (!saved) return;
        target = saved;
      }
      if (!target?.id) return;

      const { data } = await pageService.previewToken(target.id);
      const path = `${PATHS.page(target.slug)}?preview=${data.token}`;
      if (openInNewTab(path)) return;
      if (isEdit) setRedirect({ to: path, replace: false });
      else toast.info(`Your browser blocked the new tab. The preview is at ${path}`);
    } catch (thrown) {
      toast.error(thrown?.message || 'The preview link could not be created.');
    } finally {
      setPreviewing(false);
    }
  };

  const title = isEdit ? (stored?.title ?? 'Edit page') : 'New page';
  const published = values.status === 'published';
  const saving = form.submitting || publishing !== null;

  const menuOptions = useMemo(() => {
    const options = menus.map((menu) => ({
      value: menu.slug,
      label: menu.isActive === false ? `${menu.name} (hidden)` : menu.name,
    }));
    // A menu the page names that the list does not hold: still loading, not
    // loaded, or deleted in another tab. Offered by its key so the select
    // shows it — and called "not found" only when the list did arrive.
    if (values.headerMenu && !options.some((option) => option.value === values.headerMenu)) {
      options.push({
        value: values.headerMenu,
        label: menusLoading
          ? 'Loading…'
          : menusError
            ? values.headerMenu
            : `${values.headerMenu} (not found)`,
      });
    }
    return options;
  }, [menus, menusError, menusLoading, values.headerMenu]);

  const chosenMenu = menus.find((menu) => menu.slug === values.headerMenu) ?? null;
  const submenuOptions = (chosenMenu?.submenus ?? []).map((entry) => ({
    value: entry.slug,
    label: entry.name,
  }));

  const actions = (
    <>
      <Button variant="ghost" to={PATHS.adminPages} disabled={saving}>
        Cancel
      </Button>
      {system ? (
        <Button
          variant="outline"
          href={PATHS.page(stored.slug)}
          target="_blank"
          rel="noopener noreferrer"
          icon={<Icon icon="mdi:open-in-new" width="18" height="18" />}
        >
          View on the site
        </Button>
      ) : (
        <Button
          variant="outline"
          onClick={saveAndPreview}
          loading={previewing}
          disabled={saving}
          icon={<Icon icon="mdi:eye-outline" width="18" height="18" />}
        >
          {!isEdit || form.dirty ? 'Save & preview' : 'Preview'}
        </Button>
      )}
      {published || system ? null : (
        <Button variant="outline" onClick={publish} disabled={saving || previewing}>
          Publish
        </Button>
      )}
      <Button onClick={() => save()} loading={form.submitting} disabled={previewing}>
        Save
      </Button>
    </>
  );

  if (isEdit && (loading || (!stored && !error && record))) {
    return (
      <>
        <PageHeader title="Edit page" />
        <div className={styles.loading} role="status" aria-busy="true" aria-live="polite">
          <span className={styles.srOnly}>Loading the page…</span>
          <FormSection title="Basics">
            <FormColumn half>
              <Skeleton variant="rounded" height={64} />
            </FormColumn>
            <FormColumn half>
              <Skeleton variant="rounded" height={64} />
            </FormColumn>
            <FormColumn>
              <Skeleton variant="rounded" height={320} />
            </FormColumn>
          </FormSection>
        </div>
      </>
    );
  }

  if (isEdit && (error || !record)) {
    return (
      <>
        <PageHeader title="Edit page" />
        <ErrorState
          title="We could not load this page"
          text={error?.message}
          onRetry={refetch}
          action={
            error?.status === 404 ? (
              <Button variant="outline" to={PATHS.adminPages}>
                Back to pages
              </Button>
            ) : undefined
          }
        />
      </>
    );
  }

  const managedAt = builtIn?.manage ? MANAGED_AT[builtIn.manage] : null;

  return (
    <>
      <PageHeader
        title={title}
        breadcrumbs={[{ label: 'Pages', to: PATHS.adminPages }, { label: title }]}
        actions={<div className={styles.headerActions}>{actions}</div>}
      />

      <form
        ref={formRef}
        className={styles.form}
        noValidate
        onSubmit={(event) => {
          event.preventDefault();
          save();
        }}
      >
        {system ? (
          <p className={styles.banner} role="note">
            <Icon icon="mdi:auto-fix" width="18" height="18" aria-hidden="true" />
            <span>
              A built-in page: the site generates it from {builtIn?.builtFrom ?? 'its own data'}.
              Its name, its place in the menus and its order are edited here.
            </span>
          </p>
        ) : null}

        <FormSection title="Basics">
          <FormColumn half>
            <TextField
              label={system ? 'Name' : 'Title'}
              required
              maxLength={PAGE_TITLE_MAX_LENGTH}
              value={values.title ?? ''}
              error={errors.title}
              disabled={saving}
              hint={
                system
                  ? 'What the menus and this list call the page.'
                  : 'The page’s heading and the name it carries in menus.'
              }
              onChange={(event) => setField('title', event.target.value)}
              onBlur={() => form.handleBlur('title')}
            />
          </FormColumn>
          <FormColumn half id="page-slug">
            {lockedSlug ? (
              <TextField
                label="URL"
                value={PATHS.page(stored.slug)}
                readOnly
                disabled
                hint={lockedSlug}
              />
            ) : (
              <>
                <SlugField
                  label="URL"
                  required
                  path
                  base="/"
                  value={values.slug ?? ''}
                  source={values.title ?? ''}
                  error={errors.slug}
                  disabled={saving}
                  excludeId={id}
                  checkSlug={checkPageSlug}
                  onChange={(next) => setField('slug', next)}
                />
                <p className={styles.slugHint}>
                  Slashes are allowed: <code>buyer-assistance/home-loan</code> is one page at that
                  whole path. These first segments belong to the site itself and cannot be used:{' '}
                  {RESERVED_PATH_PREFIXES.join(', ')}.
                </p>
                {slugMoved ? (
                  <div className={styles.slugWarning} role="note">
                    <p>
                      <Icon icon="mdi:alert-outline" width="16" height="16" aria-hidden="true" />{' '}
                      This page is live at <code>{PATHS.page(liveSlug)}</code>. Once saved, that
                      address stops answering
                      {canRedirect ? '.' : ' — ask an SEO editor to redirect it.'}
                    </p>
                    {canRedirect ? (
                      <SwitchField
                        label={`Send visitors from ${PATHS.page(liveSlug)} to the new address (301)`}
                        checked={redirectOld}
                        disabled={saving}
                        onChange={setRedirectOld}
                      />
                    ) : null}
                  </div>
                ) : null}
              </>
            )}
          </FormColumn>

          <FormColumn half>
            <SelectField
              label="Template"
              required
              options={system ? PAGE_TEMPLATES.options : WRITTEN_TEMPLATES}
              value={values.template ?? 'standard'}
              error={errors.template}
              disabled={saving || system}
              hint={
                system
                  ? 'Built-in pages keep their template.'
                  : 'A hint for later layout work; it does not change the blocks.'
              }
              onChange={(event) => setField('template', event.target.value)}
            />
          </FormColumn>
          <FormColumn half>
            <RadioGroup
              label="Status"
              options={PAGE_STATUS.options}
              // A disabled fieldset disables every radio in it.
              disabled={system}
              value={values.status ?? 'draft'}
              error={errors.status}
              hint={
                system
                  ? unpublishRefusal(stored)
                  : home
                    ? 'A draft home record hides the two bands it gives the home page; the page itself stays up.'
                    : 'A draft answers 404 to visitors; “Save & preview” opens it anyway.'
              }
              onChange={(next) => setField('status', next)}
            />
          </FormColumn>

          {system ? null : (
            <>
              <FormColumn>
                <FormFieldControl
                  field={{
                    name: 'heroImageUrl',
                    type: 'image',
                    label: 'Hero image',
                    hint: 'hero',
                  }}
                  form={form}
                  disabled={form.submitting}
                />
              </FormColumn>

              <FormColumn half>
                <SelectField
                  label="Default lead source"
                  options={[{ value: '', label: 'None' }, ...LEAD_SOURCES.options]}
                  value={values.leadSource ?? ''}
                  error={errors.leadSource}
                  disabled={saving}
                  hint="What the page’s own buttons file enquiries as — the packages cards and any call-to-action block that does not name its own."
                  onChange={(event) => setField('leadSource', event.target.value)}
                />
              </FormColumn>
            </>
          )}
        </FormSection>

        <FormSection
          title="Placement"
          description="Where this page appears in the site’s own navigation. A page left out of both is still reachable at its URL."
        >
          <FormColumn half>
            <FormFieldControl
              field={{
                name: 'showInHeader',
                type: 'switch',
                label: 'Show in the header menu',
              }}
              form={form}
              disabled={form.submitting}
            />
          </FormColumn>
          <FormColumn half>
            <SelectField
              label="Header menu"
              options={menuOptions}
              placeholder="Select a menu"
              value={values.headerMenu ?? ''}
              disabled={saving || !values.showInHeader}
              error={
                errors.headerMenu ??
                (menusError && values.showInHeader ? (
                  <>
                    The header’s menus could not be loaded.{' '}
                    <button type="button" className={styles.inlineButton} onClick={refetchMenus}>
                      Try again
                    </button>
                  </>
                ) : undefined)
              }
              hint={
                <>
                  Any menu of the header.{' '}
                  <a
                    href={PATHS.adminPageMenus}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.inlineLink}
                  >
                    Add or change menus
                  </a>{' '}
                  in a new tab — they are offered here when you come back.
                </>
              }
              onChange={(event) => {
                setField('headerMenu', event.target.value);
                // A submenu belongs to its menu.
                setField('headerSubmenu', '');
              }}
            />
          </FormColumn>
          {values.showInHeader && submenuOptions.length > 0 ? (
            <>
              <FormColumn half />
              <FormColumn half>
                <SelectField
                  label="Submenu"
                  options={[{ value: '', label: 'None — the menu’s own list' }, ...submenuOptions]}
                  value={values.headerSubmenu ?? ''}
                  error={errors.headerSubmenu}
                  disabled={saving}
                  hint={`The group of “${chosenMenu.name}” this page is listed under.`}
                  onChange={(event) => setField('headerSubmenu', event.target.value)}
                />
              </FormColumn>
            </>
          ) : null}

          <FormColumn half>
            <FormFieldControl
              field={{
                name: 'showInFooter',
                type: 'switch',
                label: 'Show in the footer',
              }}
              form={form}
              disabled={form.submitting}
            />
          </FormColumn>
          <FormColumn half>
            <SelectField
              label="Footer column"
              options={FOOTER_COLUMNS.options}
              placeholder="Select a column"
              value={values.footerColumn ?? ''}
              error={errors.footerColumn}
              disabled={saving || !values.showInFooter}
              onChange={(event) => setField('footerColumn', event.target.value)}
            />
          </FormColumn>

          <FormColumn half>
            <FormFieldControl
              field={{
                name: 'order',
                type: 'number',
                label: 'Order',
                min: 0,
                max: PAGE_ORDER_MAX,
                hint: 'Lower comes first, in the menus and in the Pages list.',
              }}
              form={form}
              disabled={form.submitting}
            />
          </FormColumn>
        </FormSection>

        {system ? (
          <FormSection
            title="Content and search engines"
            description="The site builds this page; there is nothing to write here."
          >
            <FormColumn>
              <ul className={styles.systemNotes}>
                <li>
                  What it lists comes from {builtIn?.builtFrom ?? 'the site’s own data'}
                  {managedAt ? (
                    <>
                      {' '}
                      — edited under{' '}
                      <a href={managedAt.to} className={styles.inlineLink}>
                        {managedAt.label}
                      </a>
                    </>
                  ) : null}
                  .
                </li>
                <li>
                  Its title and description in search results come from the page-type templates of{' '}
                  <a href={PATHS.adminSeoSettings} className={styles.inlineLink}>
                    SEO → Settings
                  </a>
                  .
                </li>
              </ul>
            </FormColumn>
          </FormSection>
        ) : (
          <>
            <FormSection
              title="Content"
              description={
                home
                  ? 'The home page’s “Why choose us” (the Features block) and “How it works” (the Steps block). The rest of the home page is built from Site settings and the listings.'
                  : 'The bands the page is built from, in the order a visitor meets them.'
              }
            >
              <FormColumn id="page-content">
                <BlockEditor
                  blocks={values.blocks ?? []}
                  errors={blockErrors}
                  revealErrors={revealErrors}
                  allowedTypes={home ? homeBlockTypes(values.blocks) : undefined}
                  addNote={home ? HOME_BLOCKS_NOTE : undefined}
                  disabled={form.submitting}
                  onChange={(next) => setField('blocks', next)}
                />
              </FormColumn>
            </FormSection>

            <FormSection
              title="Search engines"
              description="The whole panel: the phrase this page targets, what a result prints, the share cards, the robots directives and the structured data."
            >
              <FormColumn>
                <SeoPanel
                  entityType="page"
                  entity={values}
                  seo={values.seo}
                  variant="full"
                  errors={errors}
                  disabled={form.submitting}
                  excludeId={id}
                  checkSlug={checkPageSlug}
                  slugBase="/"
                  fixedPath={home ? PATHS.home : undefined}
                  onFocusField={focusField}
                  onSlugChange={lockedSlug ? undefined : (slug) => setField('slug', slug)}
                  onChange={(patch, meta) => {
                    // The analysis writing its own score back is not an edit, so it
                    // moves the baseline with the value and the form stays clean
                    // until somebody actually changes something (`setComputed`).
                    if (meta?.computed) {
                      form.setComputed(toSeoPaths(patch));
                      return;
                    }
                    // One dotted path at a time: `useForm.setField` composes on the
                    // current values, so an edit and the analysis landing behind it
                    // cannot overwrite each other.
                    for (const [path, value] of Object.entries(toSeoPaths(patch))) {
                      setField(path, value);
                    }
                  }}
                />
              </FormColumn>
            </FormSection>
          </>
        )}

        <div className={styles.actionBar}>{actions}</div>
      </form>
    </>
  );
}

/**
 * The 409 of a duplicate slug, with the free variant to take.
 *
 * The API answers `{ message, errors: { slug } }` but no suggestion, and the
 * suggestion is the useful half — so it is fetched from `check-slug` and put in
 * front of the field that caused it (§5.9).
 */
async function withSlugSuggestion(thrown, slug, excludeId) {
  if (thrown?.status !== 409 || !slug) return thrown;

  try {
    const { data } = await pageService.checkSlug({ slug, excludeId });
    if (!data?.suggestion || data.suggestion === slug) return thrown;

    return new ApiError({
      status: thrown.status,
      message: thrown.message,
      data: thrown.data,
      original: thrown,
      errors: { ...thrown.errors, slug: [`${thrown.message} Try “${data.suggestion}”.`] },
    });
  } catch {
    // The suggestion is a nicety; the refusal is the answer.
    return thrown;
  }
}
