<?php

/*
 * Enums — src/config/enums.js (contract 00d22a1).
 *
 * Generated by laravel/scripts/export-contract.cjs — do not edit by hand.
 */

return [
    'LISTING_TYPES' => [
        'values' => [
            'sale',
            'rent',
            'lease',
        ],
        'entries' => [
            [
                'value' => 'sale',
                'label' => 'Buy',
                'verb' => 'for Sale',
            ],
            [
                'value' => 'rent',
                'label' => 'Rent',
                'verb' => 'for Rent',
            ],
            [
                'value' => 'lease',
                'label' => 'Lease',
                'verb' => 'for Lease',
            ],
        ],
    ],
    'SEGMENTS' => [
        'values' => [
            'residential',
            'commercial',
            'land',
        ],
        'entries' => [
            [
                'value' => 'residential',
                'label' => 'Residential',
            ],
            [
                'value' => 'commercial',
                'label' => 'Commercial',
            ],
            [
                'value' => 'land',
                'label' => 'Plots & Land',
            ],
        ],
    ],
    'CONSTRUCTION_STATUS' => [
        'values' => [
            'pre-launch',
            'under-construction',
            'ready-to-move',
            'resale',
        ],
        'entries' => [
            [
                'value' => 'pre-launch',
                'label' => 'Pre-Launch',
            ],
            [
                'value' => 'under-construction',
                'label' => 'Under Construction',
            ],
            [
                'value' => 'ready-to-move',
                'label' => 'Ready to Move',
            ],
            [
                'value' => 'resale',
                'label' => 'Resale',
            ],
        ],
    ],
    'AVAILABILITY' => [
        'values' => [
            'available',
            'sold',
            'rented',
            'reserved',
        ],
        'entries' => [
            [
                'value' => 'available',
                'label' => 'Available',
                'tone' => 'success',
            ],
            [
                'value' => 'sold',
                'label' => 'Sold',
                'tone' => 'neutral',
            ],
            [
                'value' => 'rented',
                'label' => 'Rented',
                'tone' => 'neutral',
            ],
            [
                'value' => 'reserved',
                'label' => 'Reserved',
                'tone' => 'warning',
            ],
        ],
    ],
    'FURNISHING' => [
        'values' => [
            'unfurnished',
            'semi-furnished',
            'fully-furnished',
        ],
        'entries' => [
            [
                'value' => 'unfurnished',
                'label' => 'Unfurnished',
            ],
            [
                'value' => 'semi-furnished',
                'label' => 'Semi-furnished',
            ],
            [
                'value' => 'fully-furnished',
                'label' => 'Fully furnished',
            ],
        ],
    ],
    'FACING' => [
        'values' => [
            'north',
            'south',
            'east',
            'west',
            'north-east',
            'north-west',
            'south-east',
            'south-west',
        ],
        'entries' => [
            [
                'value' => 'north',
                'label' => 'North',
            ],
            [
                'value' => 'south',
                'label' => 'South',
            ],
            [
                'value' => 'east',
                'label' => 'East',
            ],
            [
                'value' => 'west',
                'label' => 'West',
            ],
            [
                'value' => 'north-east',
                'label' => 'North-East',
            ],
            [
                'value' => 'north-west',
                'label' => 'North-West',
            ],
            [
                'value' => 'south-east',
                'label' => 'South-East',
            ],
            [
                'value' => 'south-west',
                'label' => 'South-West',
            ],
        ],
    ],
    'OWNERSHIP' => [
        'values' => [
            'freehold',
            'leasehold',
            'co-operative-society',
            'power-of-attorney',
        ],
        'entries' => [
            [
                'value' => 'freehold',
                'label' => 'Freehold',
            ],
            [
                'value' => 'leasehold',
                'label' => 'Leasehold',
            ],
            [
                'value' => 'co-operative-society',
                'label' => 'Co-operative Society',
            ],
            [
                'value' => 'power-of-attorney',
                'label' => 'Power of Attorney',
            ],
        ],
    ],
    'KITCHEN_TYPES' => [
        'values' => [
            'modular',
            'semi-modular',
            'regular',
        ],
        'entries' => [
            [
                'value' => 'modular',
                'label' => 'Modular',
            ],
            [
                'value' => 'semi-modular',
                'label' => 'Semi-modular',
            ],
            [
                'value' => 'regular',
                'label' => 'Regular',
            ],
        ],
    ],
    'AREA_UNITS' => [
        'values' => [
            'sqft',
            'sqm',
            'sqyd',
            'acre',
            'cent',
            'guntha',
        ],
        'entries' => [
            [
                'value' => 'sqft',
                'label' => 'sq ft',
                'sqftFactor' => 1,
            ],
            [
                'value' => 'sqm',
                'label' => 'sq m',
                'sqftFactor' => 10.7639,
            ],
            [
                'value' => 'sqyd',
                'label' => 'sq yd',
                'sqftFactor' => 9,
            ],
            [
                'value' => 'acre',
                'label' => 'acre',
                'sqftFactor' => 43560,
            ],
            [
                'value' => 'cent',
                'label' => 'cent',
                'sqftFactor' => 435.6,
            ],
            [
                'value' => 'guntha',
                'label' => 'guntha',
                'sqftFactor' => 1089,
            ],
        ],
    ],
    'BEDROOM_OPTIONS' => [
        'values' => [
            1,
            2,
            3,
            4,
            5,
        ],
        'entries' => [
            [
                'value' => 1,
                'label' => '1 BHK',
            ],
            [
                'value' => 2,
                'label' => '2 BHK',
            ],
            [
                'value' => 3,
                'label' => '3 BHK',
            ],
            [
                'value' => 4,
                'label' => '4 BHK',
            ],
            [
                'value' => 5,
                'label' => '5+ BHK',
            ],
        ],
    ],
    'PRICE_BUCKETS_SALE' => [
        [
            'min' => 0,
            'max' => 2500000,
            'label' => 'Up to ₹25 L',
        ],
        [
            'min' => 2500000,
            'max' => 5000000,
            'label' => '₹25 L – ₹50 L',
        ],
        [
            'min' => 5000000,
            'max' => 7500000,
            'label' => '₹50 L – ₹75 L',
        ],
        [
            'min' => 7500000,
            'max' => 10000000,
            'label' => '₹75 L – ₹1 Cr',
        ],
        [
            'min' => 10000000,
            'max' => 15000000,
            'label' => '₹1 Cr – ₹1.5 Cr',
        ],
        [
            'min' => 15000000,
            'max' => 25000000,
            'label' => '₹1.5 Cr – ₹2.5 Cr',
        ],
        [
            'min' => 25000000,
            'max' => 50000000,
            'label' => '₹2.5 Cr – ₹5 Cr',
        ],
        [
            'min' => 50000000,
            'max' => 100000000,
            'label' => '₹5 Cr – ₹10 Cr',
        ],
        [
            'min' => 100000000,
            'max' => null,
            'label' => '₹10 Cr+',
        ],
    ],
    'PRICE_BUCKETS_RENT' => [
        [
            'min' => 0,
            'max' => 10000,
            'label' => 'Up to ₹10 K',
        ],
        [
            'min' => 10000,
            'max' => 20000,
            'label' => '₹10 K – ₹20 K',
        ],
        [
            'min' => 20000,
            'max' => 35000,
            'label' => '₹20 K – ₹35 K',
        ],
        [
            'min' => 35000,
            'max' => 50000,
            'label' => '₹35 K – ₹50 K',
        ],
        [
            'min' => 50000,
            'max' => 75000,
            'label' => '₹50 K – ₹75 K',
        ],
        [
            'min' => 75000,
            'max' => 100000,
            'label' => '₹75 K – ₹1 L',
        ],
        [
            'min' => 100000,
            'max' => 200000,
            'label' => '₹1 L – ₹2 L',
        ],
        [
            'min' => 200000,
            'max' => 500000,
            'label' => '₹2 L – ₹5 L',
        ],
        [
            'min' => 500000,
            'max' => null,
            'label' => '₹5 L+',
        ],
    ],
    'SORT_OPTIONS' => [
        'values' => [
            'relevance',
            'newest',
            'price-asc',
            'price-desc',
            'area-desc',
            'popular',
        ],
        'entries' => [
            [
                'value' => 'relevance',
                'label' => 'Relevance',
            ],
            [
                'value' => 'newest',
                'label' => 'Newest first',
            ],
            [
                'value' => 'price-asc',
                'label' => 'Price: Low to High',
            ],
            [
                'value' => 'price-desc',
                'label' => 'Price: High to Low',
            ],
            [
                'value' => 'area-desc',
                'label' => 'Area: Largest first',
            ],
            [
                'value' => 'popular',
                'label' => 'Most viewed',
            ],
        ],
    ],
    'SPEC_GROUPS' => [
        'values' => [
            'structure',
            'flooring',
            'kitchen',
            'doors-windows',
            'bathroom',
            'electrical',
            'walls-painting',
            'security',
            'lift-common-areas',
            'other',
        ],
        'entries' => [
            [
                'value' => 'structure',
                'label' => 'Structure',
            ],
            [
                'value' => 'flooring',
                'label' => 'Flooring',
            ],
            [
                'value' => 'kitchen',
                'label' => 'Kitchen',
            ],
            [
                'value' => 'doors-windows',
                'label' => 'Doors & Windows',
            ],
            [
                'value' => 'bathroom',
                'label' => 'Bathroom',
            ],
            [
                'value' => 'electrical',
                'label' => 'Electrical',
            ],
            [
                'value' => 'walls-painting',
                'label' => 'Walls & Painting',
            ],
            [
                'value' => 'security',
                'label' => 'Security',
            ],
            [
                'value' => 'lift-common-areas',
                'label' => 'Lift & Common Areas',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
            ],
        ],
    ],
    'DOCUMENT_TYPES' => [
        'values' => [
            'brochure',
            'approval',
            'legal',
            'floor-plan',
            'price-list',
            'other',
        ],
        'entries' => [
            [
                'value' => 'brochure',
                'label' => 'Brochure',
            ],
            [
                'value' => 'approval',
                'label' => 'Approval / Certificate',
            ],
            [
                'value' => 'legal',
                'label' => 'Legal',
            ],
            [
                'value' => 'floor-plan',
                'label' => 'Floor Plan',
            ],
            [
                'value' => 'price-list',
                'label' => 'Price List',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
            ],
        ],
    ],
    'TIMELINE_STATUS' => [
        'values' => [
            'completed',
            'in-progress',
            'upcoming',
        ],
        'entries' => [
            [
                'value' => 'completed',
                'label' => 'Completed',
                'tone' => 'success',
            ],
            [
                'value' => 'in-progress',
                'label' => 'In Progress',
                'tone' => 'warning',
            ],
            [
                'value' => 'upcoming',
                'label' => 'Upcoming',
                'tone' => 'neutral',
            ],
        ],
    ],
    'PROJECT_APPROVALS' => [
        'values' => [
            'bbmp',
            'bda',
            'bmrda',
            'biaapa',
            'rera',
            'other',
        ],
        'entries' => [
            [
                'value' => 'bbmp',
                'label' => 'BBMP',
            ],
            [
                'value' => 'bda',
                'label' => 'BDA',
            ],
            [
                'value' => 'bmrda',
                'label' => 'BMRDA',
            ],
            [
                'value' => 'biaapa',
                'label' => 'BIAAPA',
            ],
            [
                'value' => 'rera',
                'label' => 'RERA',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
            ],
        ],
    ],
    'NEARBY_CATEGORIES' => [
        'values' => [
            'school',
            'hospital',
            'metro',
            'railway',
            'airport',
            'mall',
            'it-park',
            'restaurant',
            'park',
            'bank',
            'other',
        ],
        'entries' => [
            [
                'value' => 'school',
                'label' => 'Schools',
                'icon' => 'mdi:school-outline',
            ],
            [
                'value' => 'hospital',
                'label' => 'Hospitals',
                'icon' => 'mdi:hospital-box-outline',
            ],
            [
                'value' => 'metro',
                'label' => 'Metro',
                'icon' => 'mdi:train-variant',
            ],
            [
                'value' => 'railway',
                'label' => 'Railway',
                'icon' => 'mdi:train',
            ],
            [
                'value' => 'airport',
                'label' => 'Airport',
                'icon' => 'mdi:airplane',
            ],
            [
                'value' => 'mall',
                'label' => 'Malls & Shopping',
                'icon' => 'mdi:shopping-outline',
            ],
            [
                'value' => 'it-park',
                'label' => 'IT Parks & Offices',
                'icon' => 'mdi:office-building-outline',
            ],
            [
                'value' => 'restaurant',
                'label' => 'Restaurants',
                'icon' => 'mdi:silverware-fork-knife',
            ],
            [
                'value' => 'park',
                'label' => 'Parks',
                'icon' => 'mdi:tree-outline',
            ],
            [
                'value' => 'bank',
                'label' => 'Banks & ATMs',
                'icon' => 'mdi:bank-outline',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
                'icon' => 'mdi:map-marker-outline',
            ],
        ],
    ],
    'SECTION_VISIBILITY_KEYS' => [
        [
            'key' => 'overview',
            'label' => 'Overview',
        ],
        [
            'key' => 'highlights',
            'label' => 'Highlights',
        ],
        [
            'key' => 'specifications',
            'label' => 'Specifications',
        ],
        [
            'key' => 'amenities',
            'label' => 'Amenities',
        ],
        [
            'key' => 'unitConfigurations',
            'label' => 'Unit Configurations',
        ],
        [
            'key' => 'floorPlans',
            'label' => 'Floor Plans',
        ],
        [
            'key' => 'gallery',
            'label' => 'Gallery',
        ],
        [
            'key' => 'video',
            'label' => 'Video',
        ],
        [
            'key' => 'virtualTour',
            'label' => 'Virtual Tour',
        ],
        [
            'key' => 'documents',
            'label' => 'Documents',
        ],
        [
            'key' => 'construction',
            'label' => 'Construction Progress',
        ],
        [
            'key' => 'builder',
            'label' => 'Builder',
        ],
        [
            'key' => 'nearby',
            'label' => 'Nearby Places',
        ],
        [
            'key' => 'location',
            'label' => 'Location',
        ],
        [
            'key' => 'finance',
            'label' => 'Finance & EMI',
        ],
        [
            'key' => 'faqs',
            'label' => 'FAQs',
        ],
        [
            'key' => 'similar',
            'label' => 'Similar Properties',
        ],
        [
            'key' => 'enquiry',
            'label' => 'Enquiry',
        ],
    ],
    'AMENITY_CATEGORIES' => [
        'values' => [
            'basic',
            'lifestyle',
            'safety',
            'sports',
            'kids',
            'eco',
            'convenience',
            'commercial',
        ],
        'entries' => [
            [
                'value' => 'basic',
                'label' => 'Basic',
                'icon' => 'mdi:flash-outline',
            ],
            [
                'value' => 'lifestyle',
                'label' => 'Lifestyle',
                'icon' => 'mdi:sofa-outline',
            ],
            [
                'value' => 'safety',
                'label' => 'Safety & Security',
                'icon' => 'mdi:shield-check-outline',
            ],
            [
                'value' => 'sports',
                'label' => 'Sports',
                'icon' => 'mdi:basketball',
            ],
            [
                'value' => 'kids',
                'label' => 'Kids',
                'icon' => 'mdi:teddy-bear',
            ],
            [
                'value' => 'eco',
                'label' => 'Eco-friendly',
                'icon' => 'mdi:leaf',
            ],
            [
                'value' => 'convenience',
                'label' => 'Convenience',
                'icon' => 'mdi:cart-outline',
            ],
            [
                'value' => 'commercial',
                'label' => 'Commercial',
                'icon' => 'mdi:store-outline',
            ],
        ],
    ],
    'BADGE_TONES' => [
        'values' => [
            'neutral',
            'primary',
            'success',
            'warning',
            'error',
            'info',
        ],
        'entries' => [
            [
                'value' => 'neutral',
                'label' => 'Neutral',
            ],
            [
                'value' => 'primary',
                'label' => 'Primary',
            ],
            [
                'value' => 'success',
                'label' => 'Success',
            ],
            [
                'value' => 'warning',
                'label' => 'Warning',
            ],
            [
                'value' => 'error',
                'label' => 'Error',
            ],
            [
                'value' => 'info',
                'label' => 'Info',
            ],
        ],
    ],
    'LOCALITY_ZONES' => [
        'values' => [
            'north',
            'south',
            'east',
            'west',
            'central',
        ],
        'entries' => [
            [
                'value' => 'north',
                'label' => 'North',
            ],
            [
                'value' => 'south',
                'label' => 'South',
            ],
            [
                'value' => 'east',
                'label' => 'East',
            ],
            [
                'value' => 'west',
                'label' => 'West',
            ],
            [
                'value' => 'central',
                'label' => 'Central',
            ],
        ],
    ],
    'FAQ_CATEGORIES' => [
        'values' => [
            'buying',
            'selling',
            'renting',
            'home-loan',
            'legal',
            'rera',
            'nri',
            'general',
        ],
        'entries' => [
            [
                'value' => 'buying',
                'label' => 'Buying',
                'tone' => 'success',
            ],
            [
                'value' => 'selling',
                'label' => 'Selling',
                'tone' => 'warning',
            ],
            [
                'value' => 'renting',
                'label' => 'Renting',
                'tone' => 'primary',
            ],
            [
                'value' => 'home-loan',
                'label' => 'Home Loans',
                'tone' => 'info',
            ],
            [
                'value' => 'legal',
                'label' => 'Legal',
                'tone' => 'error',
            ],
            [
                'value' => 'rera',
                'label' => 'RERA',
                'tone' => 'error',
            ],
            [
                'value' => 'nri',
                'label' => 'NRI',
                'tone' => 'info',
            ],
            [
                'value' => 'general',
                'label' => 'General',
                'tone' => 'neutral',
            ],
        ],
    ],
    'PARTNER_CATEGORIES' => [
        'values' => [
            'developer',
            'bank',
            'legal',
            'interior',
            'other',
        ],
        'entries' => [
            [
                'value' => 'developer',
                'label' => 'Developer',
            ],
            [
                'value' => 'bank',
                'label' => 'Bank',
            ],
            [
                'value' => 'legal',
                'label' => 'Legal',
            ],
            [
                'value' => 'interior',
                'label' => 'Interior',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
            ],
        ],
    ],
    'LEAD_STATUS' => [
        'values' => [
            'new',
            'contacted',
            'qualified',
            'site-visit',
            'negotiation',
            'converted',
            'lost',
        ],
        'entries' => [
            [
                'value' => 'new',
                'label' => 'New',
                'tone' => 'info',
                'icon' => 'mdi:new-box',
            ],
            [
                'value' => 'contacted',
                'label' => 'Contacted',
                'tone' => 'warning',
                'icon' => 'mdi:phone-check-outline',
            ],
            [
                'value' => 'qualified',
                'label' => 'Qualified',
                'tone' => 'info',
                'icon' => 'mdi:check-decagram-outline',
            ],
            [
                'value' => 'site-visit',
                'label' => 'Site Visit',
                'tone' => 'primary',
                'icon' => 'mdi:map-marker-check-outline',
            ],
            [
                'value' => 'negotiation',
                'label' => 'Negotiation',
                'tone' => 'warning',
                'icon' => 'mdi:handshake-outline',
            ],
            [
                'value' => 'converted',
                'label' => 'Converted',
                'tone' => 'success',
                'icon' => 'mdi:check-circle-outline',
            ],
            [
                'value' => 'lost',
                'label' => 'Lost',
                'tone' => 'error',
                'icon' => 'mdi:close-circle-outline',
            ],
        ],
    ],
    'LEAD_PIPELINE' => [
        'new',
        'contacted',
        'qualified',
        'site-visit',
        'negotiation',
        'converted',
    ],
    'LEAD_PRIORITY' => [
        'values' => [
            'low',
            'medium',
            'high',
        ],
        'entries' => [
            [
                'value' => 'low',
                'label' => 'Low',
                'tone' => 'neutral',
            ],
            [
                'value' => 'medium',
                'label' => 'Medium',
                'tone' => 'info',
            ],
            [
                'value' => 'high',
                'label' => 'High',
                'tone' => 'error',
            ],
        ],
    ],
    'LEAD_SOURCES' => [
        'values' => [
            'property-enquiry',
            'brochure-download',
            'floor-plan-request',
            'document-request',
            'price-request',
            'site-visit-request',
            'callback-request',
            'post-requirement',
            'contact-page',
            'home-loan',
            'financial-assessment',
            'bank-eligibility',
            'legal-assistance',
            'interior-design',
            'sell-let',
            'careers',
            'partnership',
            'flexible-workspace',
            'direct-lease-retail',
            'real-estate-awareness',
            'newsletter',
            'article',
            'faq',
            'locality-page',
            'developer-page',
            'whatsapp-click',
            'call-click',
            'hero-search',
            'walk-in',
            'phone',
            'whatsapp-inbound',
            'referral',
            'portal-99acres',
            'portal-magicbricks',
            'portal-housing',
            'other',
        ],
        'entries' => [
            [
                'value' => 'property-enquiry',
                'label' => 'Property Enquiry',
            ],
            [
                'value' => 'brochure-download',
                'label' => 'Brochure Download',
            ],
            [
                'value' => 'floor-plan-request',
                'label' => 'Floor Plan Request',
            ],
            [
                'value' => 'document-request',
                'label' => 'Document Request',
            ],
            [
                'value' => 'price-request',
                'label' => 'Price Request',
            ],
            [
                'value' => 'site-visit-request',
                'label' => 'Site Visit Request',
            ],
            [
                'value' => 'callback-request',
                'label' => 'Callback Request',
            ],
            [
                'value' => 'post-requirement',
                'label' => 'Post Requirement',
            ],
            [
                'value' => 'contact-page',
                'label' => 'Contact Page',
            ],
            [
                'value' => 'home-loan',
                'label' => 'Home Loan',
            ],
            [
                'value' => 'financial-assessment',
                'label' => 'Financial Assessment',
            ],
            [
                'value' => 'bank-eligibility',
                'label' => 'Bank Eligibility',
            ],
            [
                'value' => 'legal-assistance',
                'label' => 'Legal Assistance',
            ],
            [
                'value' => 'interior-design',
                'label' => 'Interior Design',
            ],
            [
                'value' => 'sell-let',
                'label' => 'Sell / Let',
            ],
            [
                'value' => 'careers',
                'label' => 'Careers',
            ],
            [
                'value' => 'partnership',
                'label' => 'Partnership',
            ],
            [
                'value' => 'flexible-workspace',
                'label' => 'Flexible Workspace',
            ],
            [
                'value' => 'direct-lease-retail',
                'label' => 'Direct Lease & Retail',
            ],
            [
                'value' => 'real-estate-awareness',
                'label' => 'Real Estate Awareness',
            ],
            [
                'value' => 'newsletter',
                'label' => 'Newsletter',
            ],
            [
                'value' => 'article',
                'label' => 'Article',
            ],
            [
                'value' => 'faq',
                'label' => 'FAQ',
            ],
            [
                'value' => 'locality-page',
                'label' => 'Locality Page',
            ],
            [
                'value' => 'developer-page',
                'label' => 'Developer Page',
            ],
            [
                'value' => 'whatsapp-click',
                'label' => 'WhatsApp Click',
            ],
            [
                'value' => 'call-click',
                'label' => 'Call Click',
            ],
            [
                'value' => 'hero-search',
                'label' => 'Hero Search',
            ],
            [
                'value' => 'walk-in',
                'label' => 'Walk-in',
            ],
            [
                'value' => 'phone',
                'label' => 'Phone call',
            ],
            [
                'value' => 'whatsapp-inbound',
                'label' => 'WhatsApp (inbound)',
            ],
            [
                'value' => 'referral',
                'label' => 'Referral',
            ],
            [
                'value' => 'portal-99acres',
                'label' => 'Portal: 99acres',
            ],
            [
                'value' => 'portal-magicbricks',
                'label' => 'Portal: MagicBricks',
            ],
            [
                'value' => 'portal-housing',
                'label' => 'Portal: Housing',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
            ],
        ],
    ],
    'LEGACY_LEAD_SOURCE_MAP' => [
        'property-detail-page' => 'property-enquiry',
        'property_enquiry' => 'property-enquiry',
        'property-listing-page' => 'property-enquiry',
        'child_form' => 'property-enquiry',
        'homepage-contact-form' => 'contact-page',
        'contact' => 'contact-page',
        'website' => 'contact-page',
        'home_loan' => 'home-loan',
        'legal_assistance' => 'legal-assistance',
        'interior_design' => 'interior-design',
        'sell_let' => 'sell-let',
        'flexible_workspace' => 'flexible-workspace',
        'direct_lease_retails' => 'direct-lease-retail',
        'real_estate_awareness' => 'real-estate-awareness',
        'newsletter_articles' => 'newsletter',
        'article_detail' => 'article',
        'faq_contact' => 'faq',
        'brochure_download' => 'brochure-download',
        'floorplan_download' => 'floor-plan-request',
        'floorplan_request' => 'floor-plan-request',
        'document_download' => 'document-request',
        'detailed_pricing' => 'price-request',
        'bank-eligibility-check' => 'bank-eligibility',
        'financial-assessment' => 'financial-assessment',
    ],
    'LEAD_ACTIVITY_TYPES' => [
        'values' => [
            'created',
            'status-changed',
            'assigned',
            'note-added',
            'follow-up-set',
            'contacted',
            'email-sent',
            'call-logged',
            'priority-changed',
            'whatsapp-logged',
            'site-visit-logged',
            'meeting-logged',
            'activity-logged',
            'details-updated',
            'enquired-again',
        ],
        'entries' => [
            [
                'value' => 'created',
                'label' => 'Created',
            ],
            [
                'value' => 'status-changed',
                'label' => 'Status changed',
            ],
            [
                'value' => 'assigned',
                'label' => 'Assigned',
            ],
            [
                'value' => 'note-added',
                'label' => 'Note added',
            ],
            [
                'value' => 'follow-up-set',
                'label' => 'Follow-up set',
            ],
            [
                'value' => 'contacted',
                'label' => 'Contacted',
            ],
            [
                'value' => 'email-sent',
                'label' => 'E-mail sent',
            ],
            [
                'value' => 'call-logged',
                'label' => 'Call logged',
            ],
            [
                'value' => 'priority-changed',
                'label' => 'Priority changed',
            ],
            [
                'value' => 'whatsapp-logged',
                'label' => 'WhatsApp logged',
            ],
            [
                'value' => 'site-visit-logged',
                'label' => 'Site visit logged',
            ],
            [
                'value' => 'meeting-logged',
                'label' => 'Meeting logged',
            ],
            [
                'value' => 'activity-logged',
                'label' => 'Activity logged',
            ],
            [
                'value' => 'details-updated',
                'label' => 'Details updated',
            ],
            [
                'value' => 'enquired-again',
                'label' => 'Enquired again',
            ],
        ],
    ],
    'LEAD_CONTACT_TYPES' => [
        'values' => [
            'call',
            'whatsapp',
            'site-visit',
            'meeting',
            'other',
        ],
        'entries' => [
            [
                'value' => 'call',
                'label' => 'Call',
                'action' => 'Log call',
                'activity' => 'call-logged',
                'icon' => 'mdi:phone-outline',
            ],
            [
                'value' => 'whatsapp',
                'label' => 'WhatsApp',
                'action' => 'Log WhatsApp',
                'activity' => 'whatsapp-logged',
                'icon' => 'mdi:whatsapp',
            ],
            [
                'value' => 'site-visit',
                'label' => 'Site visit',
                'action' => 'Log site visit',
                'activity' => 'site-visit-logged',
                'icon' => 'mdi:home-map-marker',
            ],
            [
                'value' => 'meeting',
                'label' => 'Meeting',
                'action' => 'Log meeting',
                'activity' => 'meeting-logged',
                'icon' => 'mdi:account-group-outline',
            ],
            [
                'value' => 'other',
                'label' => 'Other',
                'action' => 'Log activity',
                'activity' => 'activity-logged',
                'icon' => 'mdi:note-text-outline',
            ],
        ],
    ],
    'LEAD_FOLLOW_UP' => [
        'values' => [
            'overdue',
            'today',
            'next7',
            'none',
        ],
        'entries' => [
            [
                'value' => 'overdue',
                'label' => 'Overdue',
            ],
            [
                'value' => 'today',
                'label' => 'Due today',
            ],
            [
                'value' => 'next7',
                'label' => 'Due in the next 7 days',
            ],
            [
                'value' => 'none',
                'label' => 'No next step',
            ],
        ],
    ],
    'LEAD_AUTO_ASSIGN' => [
        'values' => [
            'none',
            'round-robin',
            'listing-advisor',
        ],
        'entries' => [
            [
                'value' => 'none',
                'label' => 'Nobody — leads arrive unassigned',
            ],
            [
                'value' => 'round-robin',
                'label' => 'Round robin between the sales users',
            ],
            [
                'value' => 'listing-advisor',
                'label' => 'The listing’s advisor, else round robin',
            ],
        ],
    ],
    'LEAD_CLOSED_STATUSES' => [
        'converted',
        'lost',
    ],
    'LEAD_OPEN_STATUSES' => [
        'new',
        'contacted',
        'qualified',
        'site-visit',
        'negotiation',
    ],
    'ADMIN_LEAD_SOURCES' => [
        'walk-in',
        'phone',
        'whatsapp-inbound',
        'referral',
        'portal-99acres',
        'portal-magicbricks',
        'portal-housing',
    ],
    'SITE_LEAD_SOURCES' => [
        'property-enquiry',
        'brochure-download',
        'floor-plan-request',
        'document-request',
        'price-request',
        'site-visit-request',
        'callback-request',
        'post-requirement',
        'contact-page',
        'home-loan',
        'financial-assessment',
        'bank-eligibility',
        'legal-assistance',
        'interior-design',
        'sell-let',
        'careers',
        'partnership',
        'flexible-workspace',
        'direct-lease-retail',
        'real-estate-awareness',
        'newsletter',
        'article',
        'faq',
        'locality-page',
        'developer-page',
        'whatsapp-click',
        'call-click',
        'hero-search',
        'other',
    ],
    'SITE_LEAD_SOURCE_OPTIONS' => [
        [
            'value' => 'property-enquiry',
            'label' => 'Property Enquiry',
        ],
        [
            'value' => 'brochure-download',
            'label' => 'Brochure Download',
        ],
        [
            'value' => 'floor-plan-request',
            'label' => 'Floor Plan Request',
        ],
        [
            'value' => 'document-request',
            'label' => 'Document Request',
        ],
        [
            'value' => 'price-request',
            'label' => 'Price Request',
        ],
        [
            'value' => 'site-visit-request',
            'label' => 'Site Visit Request',
        ],
        [
            'value' => 'callback-request',
            'label' => 'Callback Request',
        ],
        [
            'value' => 'post-requirement',
            'label' => 'Post Requirement',
        ],
        [
            'value' => 'contact-page',
            'label' => 'Contact Page',
        ],
        [
            'value' => 'home-loan',
            'label' => 'Home Loan',
        ],
        [
            'value' => 'financial-assessment',
            'label' => 'Financial Assessment',
        ],
        [
            'value' => 'bank-eligibility',
            'label' => 'Bank Eligibility',
        ],
        [
            'value' => 'legal-assistance',
            'label' => 'Legal Assistance',
        ],
        [
            'value' => 'interior-design',
            'label' => 'Interior Design',
        ],
        [
            'value' => 'sell-let',
            'label' => 'Sell / Let',
        ],
        [
            'value' => 'careers',
            'label' => 'Careers',
        ],
        [
            'value' => 'partnership',
            'label' => 'Partnership',
        ],
        [
            'value' => 'flexible-workspace',
            'label' => 'Flexible Workspace',
        ],
        [
            'value' => 'direct-lease-retail',
            'label' => 'Direct Lease & Retail',
        ],
        [
            'value' => 'real-estate-awareness',
            'label' => 'Real Estate Awareness',
        ],
        [
            'value' => 'newsletter',
            'label' => 'Newsletter',
        ],
        [
            'value' => 'article',
            'label' => 'Article',
        ],
        [
            'value' => 'faq',
            'label' => 'FAQ',
        ],
        [
            'value' => 'locality-page',
            'label' => 'Locality Page',
        ],
        [
            'value' => 'developer-page',
            'label' => 'Developer Page',
        ],
        [
            'value' => 'whatsapp-click',
            'label' => 'WhatsApp Click',
        ],
        [
            'value' => 'call-click',
            'label' => 'Call Click',
        ],
        [
            'value' => 'hero-search',
            'label' => 'Hero Search',
        ],
        [
            'value' => 'other',
            'label' => 'Other',
        ],
    ],
    'REQUIREMENT_TIMELINES' => [
        'values' => [
            'immediate',
            '1-3-months',
            '3-6-months',
            '6-12-months',
            'exploring',
        ],
        'entries' => [
            [
                'value' => 'immediate',
                'label' => 'Immediately',
            ],
            [
                'value' => '1-3-months',
                'label' => '1–3 months',
            ],
            [
                'value' => '3-6-months',
                'label' => '3–6 months',
            ],
            [
                'value' => '6-12-months',
                'label' => '6–12 months',
            ],
            [
                'value' => 'exploring',
                'label' => 'Just exploring',
            ],
        ],
    ],
    'ARTICLE_STATUS' => [
        'values' => [
            'draft',
            'scheduled',
            'published',
            'archived',
        ],
        'entries' => [
            [
                'value' => 'draft',
                'label' => 'Draft',
                'tone' => 'neutral',
            ],
            [
                'value' => 'scheduled',
                'label' => 'Scheduled',
                'tone' => 'info',
            ],
            [
                'value' => 'published',
                'label' => 'Published',
                'tone' => 'success',
            ],
            [
                'value' => 'archived',
                'label' => 'Archived',
                'tone' => 'warning',
            ],
        ],
    ],
    'PAGE_STATUS' => [
        'values' => [
            'draft',
            'published',
        ],
        'entries' => [
            [
                'value' => 'draft',
                'label' => 'Draft',
                'tone' => 'neutral',
            ],
            [
                'value' => 'published',
                'label' => 'Published',
                'tone' => 'success',
            ],
        ],
    ],
    'PAGE_TEMPLATES' => [
        'values' => [
            'standard',
            'service',
            'about',
            'contact',
            'careers',
            'awareness',
            'legal',
            'landing',
            'system',
        ],
        'entries' => [
            [
                'value' => 'standard',
                'label' => 'Standard',
            ],
            [
                'value' => 'service',
                'label' => 'Service',
            ],
            [
                'value' => 'about',
                'label' => 'About',
            ],
            [
                'value' => 'contact',
                'label' => 'Contact',
            ],
            [
                'value' => 'careers',
                'label' => 'Careers',
            ],
            [
                'value' => 'awareness',
                'label' => 'Awareness',
            ],
            [
                'value' => 'legal',
                'label' => 'Legal',
            ],
            [
                'value' => 'landing',
                'label' => 'Landing',
            ],
            [
                'value' => 'system',
                'label' => 'Built-in',
            ],
        ],
    ],
    'HEADER_MENU_SOURCES' => [
        'values' => [
            'custom',
            'buy',
            'rent',
            'commercial',
        ],
        'entries' => [
            [
                'value' => 'custom',
                'label' => 'Pages and links',
            ],
            [
                'value' => 'buy',
                'label' => 'Buy — generated from the listings',
            ],
            [
                'value' => 'rent',
                'label' => 'Rent — generated from the property types',
            ],
            [
                'value' => 'commercial',
                'label' => 'Commercial — generated from the property types',
            ],
        ],
    ],
    'FOOTER_COLUMNS' => [
        'values' => [
            'company',
            'services',
            'insights',
        ],
        'entries' => [
            [
                'value' => 'company',
                'label' => 'Company',
            ],
            [
                'value' => 'services',
                'label' => 'Services',
            ],
            [
                'value' => 'insights',
                'label' => 'Insights',
            ],
        ],
    ],
    'BLOCK_TYPES' => [
        'values' => [
            'hero',
            'richText',
            'features',
            'steps',
            'stats',
            'faq',
            'cta',
            'leadForm',
            'team',
            'testimonials',
            'properties',
            'articles',
            'checklist',
            'quiz',
            'map',
            'contactInfo',
            'image',
            'banks',
            'partners',
            'html',
            'jobs',
            'facts',
            'expandableCards',
            'packages',
            'gallery',
        ],
        'entries' => [
            [
                'value' => 'hero',
                'label' => 'Hero',
                'icon' => 'mdi:image-area',
            ],
            [
                'value' => 'richText',
                'label' => 'Rich text',
                'icon' => 'mdi:format-text',
            ],
            [
                'value' => 'features',
                'label' => 'Features',
                'icon' => 'mdi:star-outline',
            ],
            [
                'value' => 'steps',
                'label' => 'Steps',
                'icon' => 'mdi:format-list-numbered',
            ],
            [
                'value' => 'stats',
                'label' => 'Stats',
                'icon' => 'mdi:chart-box-outline',
            ],
            [
                'value' => 'faq',
                'label' => 'FAQ',
                'icon' => 'mdi:frequently-asked-questions',
            ],
            [
                'value' => 'cta',
                'label' => 'Call to action',
                'icon' => 'mdi:bullhorn-outline',
            ],
            [
                'value' => 'leadForm',
                'label' => 'Lead form',
                'icon' => 'mdi:form-select',
            ],
            [
                'value' => 'team',
                'label' => 'Team',
                'icon' => 'mdi:account-group-outline',
            ],
            [
                'value' => 'testimonials',
                'label' => 'Testimonials',
                'icon' => 'mdi:comment-quote-outline',
            ],
            [
                'value' => 'properties',
                'label' => 'Properties',
                'icon' => 'mdi:home-city-outline',
            ],
            [
                'value' => 'articles',
                'label' => 'Articles',
                'icon' => 'mdi:newspaper-variant-outline',
            ],
            [
                'value' => 'checklist',
                'label' => 'Checklist',
                'icon' => 'mdi:format-list-checks',
            ],
            [
                'value' => 'quiz',
                'label' => 'Quiz',
                'icon' => 'mdi:comment-question-outline',
            ],
            [
                'value' => 'map',
                'label' => 'Map',
                'icon' => 'mdi:map-outline',
            ],
            [
                'value' => 'contactInfo',
                'label' => 'Contact details',
                'icon' => 'mdi:card-account-phone-outline',
            ],
            [
                'value' => 'image',
                'label' => 'Image',
                'icon' => 'mdi:image-outline',
            ],
            [
                'value' => 'banks',
                'label' => 'Banks & EMI',
                'icon' => 'mdi:bank-outline',
            ],
            [
                'value' => 'partners',
                'label' => 'Partners',
                'icon' => 'mdi:handshake-outline',
            ],
            [
                'value' => 'html',
                'label' => 'Custom HTML',
                'icon' => 'mdi:code-tags',
            ],
            [
                'value' => 'jobs',
                'label' => 'Job openings',
                'icon' => 'mdi:briefcase-outline',
            ],
            [
                'value' => 'facts',
                'label' => 'Did you know',
                'icon' => 'mdi:lightbulb-on-outline',
            ],
            [
                'value' => 'expandableCards',
                'label' => 'Expandable cards',
                'icon' => 'mdi:card-text-outline',
            ],
            [
                'value' => 'packages',
                'label' => 'Packages',
                'icon' => 'mdi:package-variant-closed',
            ],
            [
                'value' => 'gallery',
                'label' => 'Gallery',
                'icon' => 'mdi:image-multiple-outline',
            ],
        ],
    ],
    'EMPLOYMENT_TYPES' => [
        'values' => [
            'full-time',
            'part-time',
            'contract',
            'internship',
        ],
        'entries' => [
            [
                'value' => 'full-time',
                'label' => 'Full-time',
            ],
            [
                'value' => 'part-time',
                'label' => 'Part-time',
            ],
            [
                'value' => 'contract',
                'label' => 'Contract',
            ],
            [
                'value' => 'internship',
                'label' => 'Internship',
            ],
        ],
    ],
    'JOB_APPLICATION_STATUS' => [
        'values' => [
            'new',
            'shortlisted',
            'interview',
            'rejected',
            'hired',
        ],
        'entries' => [
            [
                'value' => 'new',
                'label' => 'New',
                'tone' => 'info',
            ],
            [
                'value' => 'shortlisted',
                'label' => 'Shortlisted',
                'tone' => 'primary',
            ],
            [
                'value' => 'interview',
                'label' => 'Interview',
                'tone' => 'warning',
            ],
            [
                'value' => 'rejected',
                'label' => 'Rejected',
                'tone' => 'error',
            ],
            [
                'value' => 'hired',
                'label' => 'Hired',
                'tone' => 'success',
            ],
        ],
    ],
    'MEDIA_TYPES' => [
        'values' => [
            'image',
            'video',
            'document',
        ],
        'entries' => [
            [
                'value' => 'image',
                'label' => 'Image',
            ],
            [
                'value' => 'video',
                'label' => 'Video',
            ],
            [
                'value' => 'document',
                'label' => 'Document',
            ],
        ],
    ],
    'MEDIA_PROVIDERS' => [
        'values' => [
            'cloudinary',
            'external',
        ],
        'entries' => [
            [
                'value' => 'cloudinary',
                'label' => 'Cloudinary',
            ],
            [
                'value' => 'external',
                'label' => 'External URL',
            ],
        ],
    ],
    'NEWSLETTER_STATUS' => [
        'values' => [
            'subscribed',
            'unsubscribed',
        ],
        'entries' => [
            [
                'value' => 'subscribed',
                'label' => 'Subscribed',
                'tone' => 'success',
            ],
            [
                'value' => 'unsubscribed',
                'label' => 'Unsubscribed',
                'tone' => 'neutral',
            ],
        ],
    ],
    'ROLES' => [
        'values' => [
            'admin',
            'manager',
            'sales',
        ],
        'entries' => [
            [
                'value' => 'admin',
                'label' => 'Admin',
            ],
            [
                'value' => 'manager',
                'label' => 'Manager',
            ],
            [
                'value' => 'sales',
                'label' => 'Sales',
            ],
        ],
    ],
    'HERO_SEARCH_TABS' => [
        'values' => [
            'sale',
            'rent',
            'lease',
            'commercial',
            'plots',
        ],
        'entries' => [
            [
                'value' => 'sale',
                'label' => 'Buy',
            ],
            [
                'value' => 'rent',
                'label' => 'Rent',
            ],
            [
                'value' => 'lease',
                'label' => 'Lease',
            ],
            [
                'value' => 'commercial',
                'label' => 'Commercial',
            ],
            [
                'value' => 'plots',
                'label' => 'Plots',
            ],
        ],
    ],
    'BULK_ACTIONS' => [
        'values' => [
            'activate',
            'deactivate',
            'delete',
            'feature',
            'unfeature',
            'verify',
            'unverify',
            'publish',
            'unpublish',
            'assign',
            'status',
            'priority',
            'move',
            'availability',
            'assignAgent',
            'setLocality',
            'setPropertyType',
            'setDeveloper',
        ],
        'entries' => [
            [
                'value' => 'activate',
                'label' => 'Activate',
            ],
            [
                'value' => 'deactivate',
                'label' => 'Deactivate',
            ],
            [
                'value' => 'delete',
                'label' => 'Delete',
            ],
            [
                'value' => 'feature',
                'label' => 'Feature',
            ],
            [
                'value' => 'unfeature',
                'label' => 'Remove from featured',
            ],
            [
                'value' => 'verify',
                'label' => 'Mark verified',
            ],
            [
                'value' => 'unverify',
                'label' => 'Remove verification',
            ],
            [
                'value' => 'publish',
                'label' => 'Publish',
            ],
            [
                'value' => 'unpublish',
                'label' => 'Unpublish',
            ],
            [
                'value' => 'assign',
                'label' => 'Assign',
            ],
            [
                'value' => 'status',
                'label' => 'Change status',
            ],
            [
                'value' => 'priority',
                'label' => 'Change priority',
            ],
            [
                'value' => 'move',
                'label' => 'Move to folder',
            ],
            [
                'value' => 'availability',
                'label' => 'Set availability',
            ],
            [
                'value' => 'assignAgent',
                'label' => 'Change the advisor',
            ],
            [
                'value' => 'setLocality',
                'label' => 'Change the locality',
            ],
            [
                'value' => 'setPropertyType',
                'label' => 'Change the property type',
            ],
            [
                'value' => 'setDeveloper',
                'label' => 'Change the developer',
            ],
        ],
    ],
    'SEO_SCHEMA_TYPES' => [
        'values' => [
            'auto',
            'RealEstateListing',
            'Article',
            'BlogPosting',
            'NewsArticle',
            'FAQPage',
            'WebPage',
            'Place',
            'Organization',
            'LocalBusiness',
            'Product',
            'Event',
        ],
        'entries' => [
            [
                'value' => 'auto',
                'label' => 'Automatic',
            ],
            [
                'value' => 'RealEstateListing',
                'label' => 'RealEstateListing',
            ],
            [
                'value' => 'Article',
                'label' => 'Article',
            ],
            [
                'value' => 'BlogPosting',
                'label' => 'BlogPosting',
            ],
            [
                'value' => 'NewsArticle',
                'label' => 'NewsArticle',
            ],
            [
                'value' => 'FAQPage',
                'label' => 'FAQPage',
            ],
            [
                'value' => 'WebPage',
                'label' => 'WebPage',
            ],
            [
                'value' => 'Place',
                'label' => 'Place',
            ],
            [
                'value' => 'Organization',
                'label' => 'Organization',
            ],
            [
                'value' => 'LocalBusiness',
                'label' => 'LocalBusiness',
            ],
            [
                'value' => 'Product',
                'label' => 'Product',
            ],
            [
                'value' => 'Event',
                'label' => 'Event',
            ],
        ],
    ],
    'SEO_SCORE_BANDS' => [
        'values' => [
            'good',
            'ok',
            'poor',
            'none',
        ],
        'entries' => [
            [
                'value' => 'good',
                'label' => 'Good',
                'tone' => 'success',
                'min' => 81,
                'max' => 100,
            ],
            [
                'value' => 'ok',
                'label' => 'Needs work',
                'tone' => 'warning',
                'min' => 51,
                'max' => 80,
            ],
            [
                'value' => 'poor',
                'label' => 'Poor',
                'tone' => 'error',
                'min' => 0,
                'max' => 50,
            ],
            [
                'value' => 'none',
                'label' => 'Not analysed',
                'tone' => 'neutral',
                'min' => null,
                'max' => null,
            ],
        ],
    ],
    'SEO_ENTITY_TYPES' => [
        'values' => [
            'property',
            'article',
            'page',
            'locality',
            'developer',
            'articleCategory',
            'author',
            'propertyType',
        ],
        'entries' => [
            [
                'value' => 'property',
                'label' => 'Properties',
            ],
            [
                'value' => 'article',
                'label' => 'Articles',
            ],
            [
                'value' => 'page',
                'label' => 'Pages',
            ],
            [
                'value' => 'locality',
                'label' => 'Localities',
            ],
            [
                'value' => 'developer',
                'label' => 'Developers',
            ],
            [
                'value' => 'articleCategory',
                'label' => 'Article categories',
            ],
            [
                'value' => 'author',
                'label' => 'Authors',
            ],
            [
                'value' => 'propertyType',
                'label' => 'Property types',
            ],
        ],
    ],
    'SITEMAP_CHANGEFREQ' => [
        'values' => [
            'always',
            'hourly',
            'daily',
            'weekly',
            'monthly',
            'yearly',
            'never',
        ],
        'entries' => [
            [
                'value' => 'always',
                'label' => 'Always',
            ],
            [
                'value' => 'hourly',
                'label' => 'Hourly',
            ],
            [
                'value' => 'daily',
                'label' => 'Daily',
            ],
            [
                'value' => 'weekly',
                'label' => 'Weekly',
            ],
            [
                'value' => 'monthly',
                'label' => 'Monthly',
            ],
            [
                'value' => 'yearly',
                'label' => 'Yearly',
            ],
            [
                'value' => 'never',
                'label' => 'Never',
            ],
        ],
    ],
    'SEO_TEST_STATUS' => [
        'values' => [
            'pass',
            'warn',
            'fail',
            'skip',
        ],
        'entries' => [
            [
                'value' => 'pass',
                'label' => 'Pass',
                'tone' => 'success',
            ],
            [
                'value' => 'warn',
                'label' => 'Warning',
                'tone' => 'warning',
            ],
            [
                'value' => 'fail',
                'label' => 'Fail',
                'tone' => 'error',
            ],
            [
                'value' => 'skip',
                'label' => 'Not applicable',
                'tone' => 'neutral',
            ],
        ],
    ],
    'REDIRECT_CODES' => [
        'values' => [
            301,
            302,
        ],
        'entries' => [
            [
                'value' => 301,
                'label' => '301 — Permanent',
            ],
            [
                'value' => 302,
                'label' => '302 — Temporary',
            ],
        ],
    ],
];
