<?php

namespace App\Domain\HeaderMenus;

use App\Domain\Pages\NavOrder;
use App\Support\Api\ApiException;
use App\Support\Debug\ApiLog;
use App\Support\Js;
use App\Support\Text\Slug;

/**
 * The header's menus (05_BUSINESS_RULES.md → "Header menus"; QA-56;
 * `src/config/headerMenus.js`).
 *
 * Every menu is a record: an editor renames, reorders, hides and adds them,
 * gives them submenus, and places pages and links in them. A page names its
 * menu by the menu's slug (`headerMenu`) and a group of it by the submenu's
 * slug (`headerSubmenu`), so the rules here are the ones a slug reference
 * needs:
 *
 *  - a menu keeps its slug once it exists (pages are filed under it), and its
 *    `source` — `buy`, `rent` and `commercial` are the site's generated mega
 *    menus: they come with the site, no client creates one, none is deleted;
 *  - a menu's name is unique in the header and a submenu's within its menu,
 *    ignoring case: two labels a visitor cannot tell apart are a mistake;
 *  - a submenu's slug is unique within its menu and derived from its name
 *    when sent empty; a link names one of the menu's submenus or none.
 */
final class HeaderMenuRules
{
    /** The sources whose panel the site generates from master data. */
    public const GENERATED_MENU_SOURCES = ['buy', 'rent', 'commercial'];

    /** Whether a menu's panel is generated from master data. */
    public static function isGeneratedMenu(?array $menu): bool
    {
        return in_array($menu['source'] ?? null, self::GENERATED_MENU_SOURCES, true);
    }

    /** A menu as every read answers it: with the read-only `builtIn` flag. */
    public static function withBuiltIn(array $menu): array
    {
        return [...$menu, 'builtIn' => self::isGeneratedMenu($menu)];
    }

    /** `GET /header-menus`: the active menus, left to right. */
    public static function shown(array $menus): array
    {
        $active = array_filter($menus, fn (array $menu) => ($menu['isActive'] ?? null) !== false);

        return array_map([self::class, 'withBuiltIn'], NavOrder::sort($active, 'name'));
    }

    /** Why a menu may never be deleted, or null: a generated one is hidden instead. */
    public static function deleteRefusal(array $menu): ?string
    {
        return self::isGeneratedMenu($menu)
            ? '“'.Js::string($menu['name'] ?? null).'” is generated by the site and cannot be deleted. Hide it instead.'
            : null;
    }

    /** A name as two of them are compared: trimmed, one space, any case. */
    public static function nameKey(mixed $value): string
    {
        return Js::lower(Js::collapseSpaces(Js::trim(Js::string($value ?? ''))));
    }

    /**
     * The CRUD engine's `beforeValidate`: the identity rules, the unique name,
     * the submenus as they will be stored and the links' submenus — before
     * the schema's 422 pass.
     */
    public static function prepare(array $body, array $ctx): array
    {
        $existing = $ctx['existing'] ?? null;

        if ($existing !== null) {
            $sent = $body['slug'] ?? null;
            if ($sent !== null && $sent !== '' && $sent !== $existing['slug']) {
                self::refuse(['slug' => 'A menu keeps its key: its pages are filed under it.']);
            }
            // A PUT that leaves the key out keeps it rather than deriving one from the new name.
            if (($ctx['method'] ?? null) !== 'PATCH' || array_key_exists('slug', $body)) {
                $body['slug'] = $existing['slug'];
            }
            if (array_key_exists('source', $body) && $body['source'] !== ($existing['source'] ?? null)) {
                self::refuse(['source' => self::isGeneratedMenu($existing)
                    ? 'A generated menu keeps what it is built from.'
                    : 'A menu of pages and links cannot become a generated one.']);
            }
        } elseif (array_key_exists('source', $body) && $body['source'] !== 'custom') {
            self::refuse(['source' => 'The generated menus come with the site; a new menu is made of pages and links.']);
        }

        // One label per menu in the header, whatever its case.
        if (is_string($body['name'] ?? null) && Js::trim($body['name']) !== '') {
            foreach ($ctx['store']->all('headerMenus') as $menu) {
                if (Js::string($menu['id']) !== Js::string($existing['id'] ?? '') && self::nameKey($menu['name'] ?? null) === self::nameKey($body['name'])) {
                    self::refuse(['name' => 'The header already has a menu called “'.Js::string($menu['name'] ?? null).'”. Give this one another name.']);
                }
            }
        }

        if (Js::isList($body['submenus'] ?? null)) {
            $body['submenus'] = self::settleSubmenus($body['submenus']);
        }

        // A link names one of this menu's submenus, or none.
        $known = [];
        foreach (Js::isList($body['submenus'] ?? null) ? $body['submenus'] : (array) ($existing['submenus'] ?? []) as $entry) {
            $slug = Js::get($entry, 'slug');
            if (self::truthy($slug)) {
                $known[] = $slug;
            }
        }
        if (Js::isList($body['links'] ?? null)) {
            $errors = [];
            foreach ($body['links'] as $index => $entry) {
                if (! is_array($entry) && ! is_object($entry)) {
                    continue;
                }
                $submenu = Js::get($entry, 'submenu');
                $submenu = is_string($submenu) ? Js::trim($submenu) : $submenu;
                if (self::truthy($submenu) && ! in_array($submenu, $known, true)) {
                    $errors["links.{$index}.submenu"] = 'The selected submenu is invalid.';
                }
                $body['links'][$index] = [...Js::entries($entry), 'submenu' => self::truthy($submenu) ? $submenu : null];
            }
            if ($errors !== []) {
                self::refuse($errors);
            }
        }

        return $body;
    }

    /**
     * The submenus as they will be stored: every one with a slug — derived
     * from its name when it came without one — and no slug or name twice.
     */
    public static function settleSubmenus(array $submenus): array
    {
        $slugOf = fn (mixed $entry) => is_string(Js::get($entry, 'slug')) ? Js::trim(Js::get($entry, 'slug')) : '';
        $taken = array_flip(array_filter(array_map($slugOf, $submenus), fn (string $slug) => $slug !== ''));
        $errors = [];
        $seen = [];
        $names = [];

        foreach ($submenus as $index => $entry) {
            if (! is_array($entry) && ! is_object($entry)) {
                continue;
            }
            $slug = $slugOf($entry);

            $name = self::nameKey(Js::get($entry, 'name'));
            if ($name !== '' && isset($names[$name])) {
                $errors["submenus.{$index}.name"] = 'Two submenus of one menu cannot share a name.';
            }
            $names[$name] = $index;

            if ($slug === '') {
                $base = Slug::make(Js::string(Js::get($entry, 'name') ?? ''));
                $base = $base === '' ? 'group' : $base;
                $slug = $base;
                for ($suffix = 2; isset($taken[$slug]) || isset($seen[$slug]); $suffix++) {
                    $slug = "{$base}-{$suffix}";
                }
            } elseif (isset($seen[$slug])) {
                $errors["submenus.{$index}.slug"] = 'Two submenus of one menu cannot share a key.';
            }

            $seen[$slug] = true;
            $submenus[$index] = [...Js::entries($entry), 'slug' => $slug];
        }

        if ($errors !== []) {
            self::refuse($errors);
        }

        return $submenus;
    }

    /** JavaScript's truthiness, for the values a link's submenu may arrive as. */
    private static function truthy(mixed $value): bool
    {
        return ! in_array($value, [null, false, '', 0, 0.0], true) && ! (is_float($value) && is_nan($value));
    }

    /** @param  array<string, string>  $errors */
    private static function refuse(array $errors): never
    {
        ApiLog::info('header-menus', 'Refused a menu write', ['errors' => $errors]);

        throw ApiException::validation($errors);
    }
}
