/**
 * The pages the site is made of, and the rules the admin and the API share
 * about them (00_MASTER_CONTEXT.md §6.10; `docs/DECISIONS.md`, QA-56).
 *
 * Admin → Pages listed the fifteen pages an editor writes and nothing else, so
 * the pages a visitor meets most — Buy, Rent, Localities, Articles — were
 * nowhere in it, and could not be put in a menu. They are records now too:
 * **built-in** pages, template `system`, one per page the site generates from
 * its own data. Their content is not edited here (a listing is built from the
 * listings), but their name, their place in the header and the footer and
 * their order are, exactly like a written page's.
 *
 * Two kinds of page are **protected** — never deleted, and their address never
 * changes — because something other than a menu finds them by that address:
 *
 *   - the built-in pages, whose address is a route of the site itself;
 *   - the written pages the site's own templates link to: `home` (the home
 *     page reads its bands and its head from it, D81), `contact`, `careers`,
 *     `sell-let`, the three legal texts the footer's legal line looks up by
 *     slug, and the awareness guide, whose `insights/` prefix is reserved —
 *     deleted, it could never be made again at that address (D11).
 *
 * A protected written page may still be unpublished; a built-in page may not,
 * because its route answers whatever the record says.
 *
 * CommonJS (D36b), like `enums.js`: the mock server, the seed builder and the
 * seed validator `require` it.
 */

/** The record the home page reads its two CMS bands and its head from (D81). */
const HOME_PAGE_SLUG = 'home';

/** The template of a page the site generates rather than an editor writes. */
const SYSTEM_TEMPLATE = 'system';

/**
 * The built-in pages, in the order the seed lists them.
 *
 * `builtFrom` finishes the sentence "This page is generated by the site from
 * …" on the page form; `manage` names the admin screen that edits what the
 * page shows, when there is one.
 */
const SYSTEM_PAGES = [
  {
    slug: 'properties',
    title: 'All properties',
    builtFrom: 'every active listing, with the full filter panel',
    manage: 'properties',
  },
  { slug: 'buy', title: 'Buy', builtFrom: 'the listings for sale', manage: 'properties' },
  { slug: 'rent', title: 'Rent', builtFrom: 'the listings to rent', manage: 'properties' },
  {
    slug: 'commercial',
    title: 'Commercial',
    builtFrom: 'the commercial listings',
    manage: 'properties',
  },
  {
    slug: 'lease',
    title: 'Lease',
    builtFrom: 'the commercial listings offered on lease',
    manage: 'properties',
  },
  { slug: 'plots', title: 'Plots', builtFrom: 'the plot and land listings', manage: 'properties' },
  {
    slug: 'localities',
    title: 'Localities',
    builtFrom: 'the locality guides',
    manage: 'localities',
  },
  { slug: 'builders', title: 'Builders', builtFrom: 'the developers', manage: 'developers' },
  {
    slug: 'insights/articles',
    title: 'Articles',
    builtFrom: 'the published articles',
    manage: 'articles',
  },
  { slug: 'insights/faqs', title: 'FAQs', builtFrom: 'the active FAQs', manage: 'faqs' },
  {
    slug: 'shortlist',
    title: 'Shortlist',
    builtFrom: 'the properties a visitor has saved in their own browser',
    manage: null,
  },
];

/**
 * The written pages the site's own templates reach by their address, and why
 * each is on the list.
 */
const LINKED_PAGE_SLUGS = [
  // The home page's "Why choose us" and "How it works", and its head (D81).
  HOME_PAGE_SLUG,
  // The header's Contact, the 404 page's trail and the seeded buttons.
  'contact',
  // An opening links back to it, and its breadcrumb names it.
  'careers',
  // The home page's "List your property" band.
  'sell-let',
  // The footer's legal line looks the three up by slug.
  'privacy-policy',
  'terms-of-use',
  'disclaimer',
  // Its `insights/` prefix is reserved: deleted, it could not be made again (D11).
  'insights/real-estate-awareness',
];

const slugOf = (page) => String(page?.slug ?? '');
const titleOf = (page) => String(page?.title ?? '').trim() || slugOf(page);

/** Whether a page is one the site generates (template `system`). */
const isSystemPage = (page) => page?.template === SYSTEM_TEMPLATE;

/** Whether a page is the record behind the home page. */
const isHomePage = (page) => slugOf(page) === HOME_PAGE_SLUG;

/** Whether the site's own templates link to a written page by its address. */
const isLinkedPage = (page) => LINKED_PAGE_SLUGS.includes(slugOf(page));

/** Whether a page is never deleted and keeps its address (see the file header). */
const isProtectedPage = (page) => isSystemPage(page) || isLinkedPage(page);

/** The built-in page definition for a slug, or `null`. */
const systemPageOf = (slug) => SYSTEM_PAGES.find((page) => page.slug === slug) ?? null;

/**
 * Why a page may not be deleted, or `null` — the sentence the API's 409 and
 * the admin's refusal both use.
 *
 * @param {{slug?: string, title?: string, template?: string}} page
 * @returns {string|null}
 */
function deleteRefusal(page) {
  if (isSystemPage(page)) {
    return `“${titleOf(page)}” is built into the site and cannot be deleted. Take it out of the menus instead.`;
  }
  if (isHomePage(page)) {
    return 'The home page cannot be deleted: its “Why choose us” and “How it works” bands and its search listing are read from it.';
  }
  if (isLinkedPage(page)) {
    return `“${titleOf(page)}” cannot be deleted: the site links to it by its address. Unpublish it instead.`;
  }
  return null;
}

/**
 * Why a page's address may not change, or `null`.
 *
 * @param {{slug?: string, title?: string, template?: string}} page the stored record
 * @returns {string|null}
 */
function slugRefusal(page) {
  if (isSystemPage(page)) return 'A built-in page keeps its address: it is a route of the site.';
  if (isHomePage(page)) return 'The home page’s record keeps its address.';
  if (isLinkedPage(page)) {
    return `This page keeps its address: the site links to it as /${slugOf(page)}.`;
  }
  return null;
}

/**
 * Why a page may not be taken off the site, or `null`. Only a built-in page:
 * its route answers whatever the record says, so a "draft" would still be live.
 *
 * @param {{template?: string}} page
 * @returns {string|null}
 */
function unpublishRefusal(page) {
  return isSystemPage(page)
    ? 'A built-in page is always live: the site generates it. Take it out of the menus instead.'
    : null;
}

/**
 * Why the home page's SEO panel may not redirect it: its address is `/`, and
 * the rule would send every visitor who arrives at the site somewhere else.
 *
 * @returns {string}
 */
const homeRedirectRefusal = () =>
  'The home page cannot be redirected: its address is /, where every visitor arrives.';

module.exports = {
  HOME_PAGE_SLUG,
  SYSTEM_TEMPLATE,
  SYSTEM_PAGES,
  LINKED_PAGE_SLUGS,
  isSystemPage,
  isHomePage,
  isLinkedPage,
  isProtectedPage,
  systemPageOf,
  deleteRefusal,
  homeRedirectRefusal,
  slugRefusal,
  unpublishRefusal,
};
