-- Squares N Acres — MySQL 8 schema for the Laravel API
--
-- Generated by `npm run generate:backend-guidelines` from
-- `mock-server/schemas/models.js` and the relational mapping rules of
-- `scripts/lib/guidelines/sql.js`. Do not edit this file by hand.
-- generatedFrom: 0339713
--
-- Conventions:
--   * utf8mb4 / utf8mb4_unicode_ci, InnoDB, `id` BIGINT UNSIGNED AUTO_INCREMENT
--   * every timestamp is UTC; the API renders ISO-8601 (§5.5)
--   * enum columns are VARCHAR with the allowed values in the comment; the
--     application validates them against `src/config/enums.js`
--   * `ON DELETE RESTRICT` for master data a listing depends on,
--     `ON DELETE CASCADE` for the rows of a nested array,
--     `ON DELETE SET NULL` for an optional pointer such as `assigned_to`
--   * `deleted_at` marks the four soft-deleted tables

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- collection: cities
CREATE TABLE `cities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `state` VARCHAR(120) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cities_slug_unique` (`slug`),
  KEY `cities_is_active_index` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: localities
CREATE TABLE `localities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `city_id` BIGINT UNSIGNED NOT NULL,
  `zone` VARCHAR(40) NULL DEFAULT NULL COMMENT 'north|south|east|west|central',
  `description` LONGTEXT NULL,
  `short_description` VARCHAR(300) NOT NULL DEFAULT '',
  `hero_image_url` VARCHAR(500) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `pincodes` JSON NULL,
  `highlights` JSON NULL,
  `connectivity` JSON NULL,
  `avg_price_per_sqft` INT NULL DEFAULT NULL,
  `price_trend_note` VARCHAR(300) NULL DEFAULT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `seo` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `localities_slug_unique` (`slug`),
  KEY `localities_city_id_index` (`city_id`),
  KEY `localities_is_active_index` (`is_active`),
  KEY `localities_is_featured_index` (`is_featured`),
  KEY `localities_order_index` (`order`),
  CONSTRAINT `localities_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: segments
CREATE TABLE `segments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `kind` VARCHAR(40) NOT NULL DEFAULT 'residential' COMMENT 'residential|commercial|land',
  `description` VARCHAR(300) NULL DEFAULT NULL,
  `icon` VARCHAR(80) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `segments_slug_unique` (`slug`),
  KEY `segments_is_active_index` (`is_active`),
  KEY `segments_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: propertyTypes
CREATE TABLE `property_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `segment` VARCHAR(75) NOT NULL DEFAULT 'residential',
  `icon` VARCHAR(80) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `seo` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `property_types_slug_unique` (`slug`),
  KEY `property_types_segment_index` (`segment`),
  KEY `property_types_is_active_index` (`is_active`),
  KEY `property_types_order_index` (`order`),
  CONSTRAINT `property_types_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`slug`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: amenities
CREATE TABLE `amenities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `category` VARCHAR(40) NOT NULL DEFAULT 'basic' COMMENT 'basic|lifestyle|safety|sports|kids|eco|convenience|commercial',
  `icon` VARCHAR(80) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `amenities_slug_unique` (`slug`),
  KEY `amenities_is_active_index` (`is_active`),
  KEY `amenities_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: badges
CREATE TABLE `badges` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `color` VARCHAR(40) NOT NULL DEFAULT 'primary' COMMENT 'neutral|primary|success|warning|error|info',
  `icon` VARCHAR(80) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `badges_slug_unique` (`slug`),
  KEY `badges_is_active_index` (`is_active`),
  KEY `badges_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: developers
CREATE TABLE `developers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `logo_url` VARCHAR(500) NULL DEFAULT NULL,
  `cover_image_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` LONGTEXT NULL,
  `short_description` VARCHAR(300) NOT NULL DEFAULT '',
  `established_year` INT NULL DEFAULT NULL,
  `headquarters` VARCHAR(150) NULL DEFAULT NULL,
  `website` VARCHAR(500) NULL DEFAULT NULL,
  `total_projects` INT NULL DEFAULT NULL,
  `ongoing_projects` INT NULL DEFAULT NULL,
  `completed_projects` INT NULL DEFAULT NULL,
  `rera_ids` JSON NULL,
  `highlights` JSON NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `seo` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `developers_slug_unique` (`slug`),
  KEY `developers_is_active_index` (`is_active`),
  KEY `developers_is_featured_index` (`is_featured`),
  KEY `developers_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: banks
CREATE TABLE `banks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `logo_url` VARCHAR(500) NULL DEFAULT NULL,
  `interest_rate_min` DECIMAL(5,2) NOT NULL,
  `interest_rate_max` DECIMAL(5,2) NOT NULL,
  `processing_fee_note` VARCHAR(200) NULL DEFAULT NULL,
  `max_tenure_years` INT NOT NULL,
  `max_ltv_percent` INT NOT NULL,
  `min_loan_amount` DECIMAL(14,2) NULL DEFAULT NULL,
  `max_loan_amount` DECIMAL(14,2) NULL DEFAULT NULL,
  `features` JSON NULL,
  `apply_url` VARCHAR(500) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `banks_slug_unique` (`slug`),
  KEY `banks_is_active_index` (`is_active`),
  KEY `banks_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: adminUsers
CREATE TABLE `admin_users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(40) NOT NULL DEFAULT 'sales' COMMENT 'admin|manager|sales',
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(500) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_login_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `admin_users_is_active_index` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: teamMembers
CREATE TABLE `team_members` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `designation` VARCHAR(120) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `whatsapp` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(191) NULL DEFAULT NULL,
  `photo_url` VARCHAR(500) NULL DEFAULT NULL,
  `bio` LONGTEXT NULL,
  `rera_id` VARCHAR(80) NULL DEFAULT NULL,
  `social_links` JSON NULL,
  `order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `show_on_about` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `team_members_slug_unique` (`slug`),
  KEY `team_members_is_active_index` (`is_active`),
  KEY `team_members_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: articleCategories
CREATE TABLE `article_categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `seo` JSON NULL,
  `order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `article_categories_slug_unique` (`slug`),
  KEY `article_categories_is_active_index` (`is_active`),
  KEY `article_categories_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: articleTags
CREATE TABLE `article_tags` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `article_tags_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: authors
CREATE TABLE `authors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(75) NOT NULL,
  `designation` VARCHAR(120) NULL DEFAULT NULL,
  `bio` LONGTEXT NULL,
  `avatar_url` VARCHAR(500) NULL DEFAULT NULL,
  `email` VARCHAR(191) NULL DEFAULT NULL,
  `social_links` JSON NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `seo` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `authors_slug_unique` (`slug`),
  KEY `authors_is_active_index` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties
CREATE TABLE `properties` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(75) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `project_name` VARCHAR(150) NULL DEFAULT NULL,
  `listing_type` VARCHAR(40) NOT NULL DEFAULT 'sale' COMMENT 'sale|rent|lease',
  `segment` VARCHAR(75) NOT NULL DEFAULT 'residential',
  `property_type_id` BIGINT UNSIGNED NOT NULL,
  `construction_status` VARCHAR(40) NOT NULL DEFAULT 'ready-to-move' COMMENT 'pre-launch|under-construction|ready-to-move|resale',
  `availability` VARCHAR(40) NOT NULL DEFAULT 'available' COMMENT 'available|sold|rented|reserved',
  `possession_date` DATE NULL DEFAULT NULL,
  `age_of_property_years` INT NULL DEFAULT NULL,
  `furnishing` VARCHAR(40) NULL DEFAULT NULL COMMENT 'unfurnished|semi-furnished|fully-furnished',
  `facing` VARCHAR(40) NULL DEFAULT NULL COMMENT 'north|south|east|west|north-east|north-west|south-east|south-west',
  `floor_number` INT NULL DEFAULT NULL,
  `total_floors` INT NULL DEFAULT NULL,
  `ownership` VARCHAR(40) NULL DEFAULT NULL COMMENT 'freehold|leasehold|co-operative-society|power-of-attorney',
  `rera_number` VARCHAR(80) NULL DEFAULT NULL,
  `rera_registered` TINYINT(1) NOT NULL DEFAULT 0,
  `description` LONGTEXT NULL,
  `short_description` VARCHAR(300) NOT NULL DEFAULT '',
  `highlights` JSON NULL,
  `specifications` JSON NULL,
  `construction_specs` JSON NULL,
  `video_url` VARCHAR(500) NULL DEFAULT NULL,
  `virtual_tour_url` VARCHAR(500) NULL DEFAULT NULL,
  `brochure_url` VARCHAR(500) NULL DEFAULT NULL,
  `brochure_lead_gated` TINYINT(1) NOT NULL DEFAULT 1,
  `address` VARCHAR(300) NOT NULL DEFAULT '' COMMENT 'location.address',
  `locality_id` BIGINT UNSIGNED NOT NULL COMMENT 'location.localityId',
  `city_id` BIGINT UNSIGNED NOT NULL COMMENT 'location.cityId',
  `pincode` VARCHAR(6) NULL DEFAULT NULL COMMENT 'location.pincode',
  `landmark` VARCHAR(200) NULL DEFAULT NULL COMMENT 'location.landmark',
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL COMMENT 'location.latitude',
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL COMMENT 'location.longitude',
  `map_embed_url` VARCHAR(500) NULL DEFAULT NULL COMMENT 'location.mapEmbedUrl',
  `show_exact_location` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'location.showExactLocation',
  `price` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.price',
  `price_on_request` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'pricing.priceOnRequest',
  `price_range_min` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.priceRangeMin',
  `price_range_max` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.priceRangeMax',
  `price_per_sqft` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.pricePerSqft',
  `price_negotiable` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'pricing.priceNegotiable',
  `rent_per_month` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.rentPerMonth',
  `security_deposit` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.securityDeposit',
  `maintenance_charges_monthly` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.maintenanceChargesMonthly',
  `booking_amount` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'pricing.bookingAmount',
  `other_charges` JSON NULL COMMENT 'pricing.otherCharges',
  `currency` VARCHAR(40) NOT NULL DEFAULT 'INR' COMMENT 'INR · pricing.currency',
  `super_built_up_area` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'area.superBuiltUpArea',
  `built_up_area` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'area.builtUpArea',
  `carpet_area` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'area.carpetArea',
  `plot_area` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'area.plotArea',
  `area_unit` VARCHAR(40) NOT NULL DEFAULT 'sqft' COMMENT 'sqft|sqm|sqyd|acre|cent|guntha · area.areaUnit',
  `plot_length` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'area.plotLength',
  `plot_width` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'area.plotWidth',
  `plot_dimension_unit` VARCHAR(40) NULL DEFAULT NULL COMMENT 'sqft|sqm|sqyd|acre|cent|guntha · area.plotDimensionUnit',
  `bedrooms` INT NULL DEFAULT NULL COMMENT 'configuration.bedrooms',
  `bathrooms` INT NULL DEFAULT NULL COMMENT 'configuration.bathrooms',
  `balconies` INT NULL DEFAULT NULL COMMENT 'configuration.balconies',
  `parking_covered` INT NULL DEFAULT NULL COMMENT 'configuration.parkingCovered',
  `parking_open` INT NULL DEFAULT NULL COMMENT 'configuration.parkingOpen',
  `servant_room` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'configuration.servantRoom',
  `study_room` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'configuration.studyRoom',
  `pooja_room` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'configuration.poojaRoom',
  `kitchen_type` VARCHAR(40) NULL DEFAULT NULL COMMENT 'modular|semi-modular|regular · configuration.kitchenType',
  `developer_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'project.developerId',
  `project_total_units` INT NULL DEFAULT NULL COMMENT 'project.totalUnits',
  `project_total_towers` INT NULL DEFAULT NULL COMMENT 'project.totalTowers',
  `project_total_floors` INT NULL DEFAULT NULL COMMENT 'project.totalFloors',
  `project_area_acres` DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'project.projectAreaAcres',
  `project_open_area_percent` INT NULL DEFAULT NULL COMMENT 'project.openAreaPercent',
  `project_launch_date` DATE NULL DEFAULT NULL COMMENT 'project.launchDate',
  `project_approvals` JSON NULL COMMENT 'project.approvals',
  `is_landmark_project` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'project.landmarkProject',
  `construction_progress_percent` INT NULL DEFAULT NULL,
  `section_visibility` JSON NULL,
  `agent_team_member_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'agent.teamMemberId',
  `agent_name` VARCHAR(120) NULL DEFAULT NULL COMMENT 'agent.name',
  `agent_phone` VARCHAR(20) NULL DEFAULT NULL COMMENT 'agent.phone',
  `agent_whatsapp` VARCHAR(20) NULL DEFAULT NULL COMMENT 'agent.whatsapp',
  `agent_email` VARCHAR(191) NULL DEFAULT NULL COMMENT 'agent.email',
  `agent_photo_url` VARCHAR(500) NULL DEFAULT NULL COMMENT 'agent.photoUrl',
  `agent_show_on_listing` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'agent.showOnListing',
  `seo` JSON NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `priority_order` INT NOT NULL DEFAULT 0,
  `view_count` INT NOT NULL DEFAULT 0,
  `enquiry_count` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `updated_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL COMMENT 'soft delete',
  PRIMARY KEY (`id`),
  UNIQUE KEY `properties_slug_unique` (`slug`),
  KEY `properties_locality_id_index` (`locality_id`),
  KEY `properties_city_id_index` (`city_id`),
  KEY `properties_property_type_id_index` (`property_type_id`),
  KEY `properties_developer_id_index` (`developer_id`),
  KEY `properties_listing_type_index` (`listing_type`),
  KEY `properties_segment_index` (`segment`),
  KEY `properties_construction_status_index` (`construction_status`),
  KEY `properties_availability_index` (`availability`),
  KEY `properties_is_active_index` (`is_active`),
  KEY `properties_is_featured_index` (`is_featured`),
  KEY `properties_price_index` (`price`),
  KEY `properties_rent_per_month_index` (`rent_per_month`),
  KEY `properties_published_at_index` (`published_at`),
  FULLTEXT KEY `properties_fulltext` (`title`, `project_name`, `short_description`),
  CONSTRAINT `properties_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`slug`) ON DELETE RESTRICT,
  CONSTRAINT `properties_property_type_id_foreign` FOREIGN KEY (`property_type_id`) REFERENCES `property_types` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `properties_locality_id_foreign` FOREIGN KEY (`locality_id`) REFERENCES `localities` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `properties_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `properties_developer_id_foreign` FOREIGN KEY (`developer_id`) REFERENCES `developers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `properties_agent_team_member_id_foreign` FOREIGN KEY (`agent_team_member_id`) REFERENCES `team_members` (`id`) ON DELETE SET NULL,
  CONSTRAINT `properties_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `properties_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.images
CREATE TABLE `property_images` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `alt` VARCHAR(200) NOT NULL,
  `caption` VARCHAR(300) NULL DEFAULT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `is_cover` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_images_property_id_index` (`property_id`),
  KEY `property_images_order_index` (`order`),
  CONSTRAINT `property_images_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.documents
CREATE TABLE `property_documents` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `type` VARCHAR(40) NOT NULL DEFAULT 'other' COMMENT 'brochure|approval|legal|floor-plan|price-list|other',
  `lead_gated` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_documents_property_id_index` (`property_id`),
  KEY `property_documents_order_index` (`order`),
  CONSTRAINT `property_documents_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.floorPlans
CREATE TABLE `property_floor_plans` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `image_url` VARCHAR(500) NOT NULL,
  `pdf_url` VARCHAR(500) NULL DEFAULT NULL,
  `area` DECIMAL(14,2) NULL DEFAULT NULL,
  `area_unit` VARCHAR(40) NOT NULL DEFAULT 'sqft' COMMENT 'sqft|sqm|sqyd|acre|cent|guntha',
  `bedrooms` INT NULL DEFAULT NULL,
  `price` DECIMAL(14,2) NULL DEFAULT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_floor_plans_property_id_index` (`property_id`),
  KEY `property_floor_plans_order_index` (`order`),
  CONSTRAINT `property_floor_plans_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.unitConfigurations
CREATE TABLE `property_unit_configurations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `bedrooms` INT NULL DEFAULT NULL,
  `bathrooms` INT NULL DEFAULT NULL,
  `super_built_up_area` DECIMAL(14,2) NULL DEFAULT NULL,
  `carpet_area` DECIMAL(14,2) NULL DEFAULT NULL,
  `area_unit` VARCHAR(40) NOT NULL DEFAULT 'sqft' COMMENT 'sqft|sqm|sqyd|acre|cent|guntha',
  `price` DECIMAL(14,2) NULL DEFAULT NULL,
  `price_on_request` TINYINT(1) NOT NULL DEFAULT 0,
  `floor_plan_image_url` VARCHAR(500) NULL DEFAULT NULL,
  `floor_plan_pdf_url` VARCHAR(500) NULL DEFAULT NULL,
  `available_units` INT NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0 COMMENT 'position inside the parent array',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_unit_configurations_property_id_index` (`property_id`),
  KEY `property_unit_configurations_order_index` (`order`),
  CONSTRAINT `property_unit_configurations_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.nearbyPlaces
CREATE TABLE `property_nearby_places` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `category` VARCHAR(40) NOT NULL DEFAULT 'other' COMMENT 'school|hospital|metro|railway|airport|mall|it-park|restaurant|park|bank|other',
  `distance_km` DECIMAL(14,2) NULL DEFAULT NULL,
  `travel_time_min` INT NULL DEFAULT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_nearby_places_property_id_index` (`property_id`),
  KEY `property_nearby_places_order_index` (`order`),
  CONSTRAINT `property_nearby_places_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.constructionTimeline
CREATE TABLE `property_construction_timeline` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `milestone` VARCHAR(150) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'upcoming' COMMENT 'completed|in-progress|upcoming',
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `note` VARCHAR(300) NULL DEFAULT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_construction_timeline_property_id_index` (`property_id`),
  KEY `property_construction_timeline_order_index` (`order`),
  CONSTRAINT `property_construction_timeline_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — rows of properties.faqs
CREATE TABLE `property_faqs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `question` VARCHAR(300) NOT NULL,
  `answer` LONGTEXT NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `property_faqs_property_id_index` (`property_id`),
  KEY `property_faqs_order_index` (`order`),
  CONSTRAINT `property_faqs_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — properties.amenityIds
CREATE TABLE `property_amenity` (
  `property_id` BIGINT UNSIGNED NOT NULL,
  `amenity_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`property_id`, `amenity_id`),
  KEY `property_amenity_amenity_id_index` (`amenity_id`),
  CONSTRAINT `property_amenity_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE,
  CONSTRAINT `property_amenity_amenity_id_foreign` FOREIGN KEY (`amenity_id`) REFERENCES `amenities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — properties.badgeIds
CREATE TABLE `property_badge` (
  `property_id` BIGINT UNSIGNED NOT NULL,
  `badge_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`property_id`, `badge_id`),
  KEY `property_badge_badge_id_index` (`badge_id`),
  CONSTRAINT `property_badge_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE,
  CONSTRAINT `property_badge_badge_id_foreign` FOREIGN KEY (`badge_id`) REFERENCES `badges` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: properties — properties.similarPropertyIds
CREATE TABLE `property_similar` (
  `property_id` BIGINT UNSIGNED NOT NULL,
  `similar_property_id` BIGINT UNSIGNED NOT NULL,
  `position` INT NOT NULL DEFAULT 0 COMMENT 'the order the admin chose',
  PRIMARY KEY (`property_id`, `similar_property_id`),
  KEY `property_similar_similar_property_id_index` (`similar_property_id`),
  CONSTRAINT `property_similar_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE,
  CONSTRAINT `property_similar_similar_property_id_foreign` FOREIGN KEY (`similar_property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: articles
CREATE TABLE `articles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(75) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `excerpt` VARCHAR(300) NOT NULL DEFAULT '',
  `content` LONGTEXT NOT NULL,
  `featured_image_url` VARCHAR(500) NOT NULL COMMENT 'featuredImage.url',
  `featured_image_alt` VARCHAR(200) NOT NULL COMMENT 'featuredImage.alt',
  `featured_image_caption` VARCHAR(300) NULL DEFAULT NULL COMMENT 'featuredImage.caption',
  `category_id` BIGINT UNSIGNED NOT NULL,
  `author_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft' COMMENT 'draft|scheduled|published|archived',
  `published_at` DATETIME NULL DEFAULT NULL,
  `updated_at_display` DATETIME NULL DEFAULT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `allow_comments` TINYINT(1) NOT NULL DEFAULT 0,
  `related_article_ids` JSON NULL,
  `related_property_ids` JSON NULL,
  `faqs` JSON NULL,
  `table_of_contents` TINYINT(1) NOT NULL DEFAULT 1,
  `seo` JSON NULL,
  `content_text` LONGTEXT NULL,
  `reading_time_minutes` INT NOT NULL DEFAULT 0,
  `word_count` INT NOT NULL DEFAULT 0,
  `view_count` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL COMMENT 'soft delete',
  PRIMARY KEY (`id`),
  UNIQUE KEY `articles_slug_unique` (`slug`),
  KEY `articles_category_id_index` (`category_id`),
  KEY `articles_author_id_index` (`author_id`),
  KEY `articles_is_featured_index` (`is_featured`),
  KEY `articles_published_at_index` (`published_at`),
  KEY `articles_status_index` (`status`),
  FULLTEXT KEY `articles_fulltext` (`title`, `content_text`),
  CONSTRAINT `articles_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `article_categories` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `articles_author_id_foreign` FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: articles — articles.tagIds
CREATE TABLE `article_tag` (
  `article_id` BIGINT UNSIGNED NOT NULL,
  `article_tag_id` BIGINT UNSIGNED NOT NULL,
  `position` INT NOT NULL DEFAULT 0 COMMENT 'the order the admin chose',
  PRIMARY KEY (`article_id`, `article_tag_id`),
  KEY `article_tag_article_tag_id_index` (`article_tag_id`),
  CONSTRAINT `article_tag_article_id_foreign` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `article_tag_article_tag_id_foreign` FOREIGN KEY (`article_tag_id`) REFERENCES `article_tags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: headerMenus
CREATE TABLE `header_menus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `slug` VARCHAR(60) NOT NULL,
  `href` VARCHAR(500) NULL DEFAULT NULL,
  `source` VARCHAR(40) NOT NULL DEFAULT 'custom' COMMENT 'custom|buy|rent|commercial',
  `submenus` JSON NULL,
  `links` JSON NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `header_menus_slug_unique` (`slug`),
  KEY `header_menus_is_active_index` (`is_active`),
  KEY `header_menus_source_index` (`source`),
  KEY `header_menus_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: pages
CREATE TABLE `pages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(120) NOT NULL DEFAULT '',
  `title` VARCHAR(150) NOT NULL,
  `template` VARCHAR(40) NOT NULL DEFAULT 'standard' COMMENT 'standard|service|about|contact|careers|awareness|legal|landing|system',
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft' COMMENT 'draft|published',
  `hero_image_url` VARCHAR(500) NULL DEFAULT NULL,
  `lead_source` VARCHAR(40) NULL DEFAULT NULL COMMENT 'property-enquiry|brochure-download|floor-plan-request|document-request|price-request|site-visit-request|callback-request|post-requirement|contact-page|home-loan|financial-assessment|bank-eligibility|legal-assistance|interior-design|sell-let|careers|partnership|flexible-workspace|direct-lease-retail|real-estate-awareness|newsletter|article|faq|locality-page|developer-page|whatsapp-click|call-click|hero-search|other',
  `seo` JSON NULL,
  `order` INT NOT NULL DEFAULT 0,
  `show_in_footer` TINYINT(1) NOT NULL DEFAULT 0,
  `footer_column` VARCHAR(40) NULL DEFAULT NULL COMMENT 'company|services|insights',
  `show_in_header` TINYINT(1) NOT NULL DEFAULT 0,
  `header_menu` VARCHAR(60) NULL DEFAULT NULL,
  `header_submenu` VARCHAR(75) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL COMMENT 'soft delete',
  PRIMARY KEY (`id`),
  KEY `pages_status_index` (`status`),
  KEY `pages_order_index` (`order`),
  CONSTRAINT `pages_header_menu_foreign` FOREIGN KEY (`header_menu`) REFERENCES `header_menus` (`slug`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: pages — rows of pages.blocks
CREATE TABLE `page_blocks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `page_id` BIGINT UNSIGNED NOT NULL,
  `type` VARCHAR(40) NOT NULL COMMENT 'hero|richText|features|steps|stats|faq|cta|leadForm|team|testimonials|properties|articles|checklist|quiz|map|contactInfo|image|banks|partners|html|jobs|facts|expandableCards|packages|gallery',
  `order` INT NOT NULL DEFAULT 0,
  `data` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `page_blocks_page_id_index` (`page_id`),
  KEY `page_blocks_order_index` (`order`),
  CONSTRAINT `page_blocks_page_id_foreign` FOREIGN KEY (`page_id`) REFERENCES `pages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: faqs
CREATE TABLE `faqs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(300) NOT NULL,
  `answer` LONGTEXT NOT NULL,
  `category` VARCHAR(40) NOT NULL DEFAULT 'general' COMMENT 'buying|selling|renting|home-loan|legal|rera|nri|general',
  `order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `show_on_home` TINYINT(1) NOT NULL DEFAULT 0,
  `property_type_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `faqs_property_type_id_index` (`property_type_id`),
  KEY `faqs_is_active_index` (`is_active`),
  KEY `faqs_order_index` (`order`),
  CONSTRAINT `faqs_property_type_id_foreign` FOREIGN KEY (`property_type_id`) REFERENCES `property_types` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: testimonials
CREATE TABLE `testimonials` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `designation` VARCHAR(120) NULL DEFAULT NULL,
  `location` VARCHAR(120) NULL DEFAULT NULL,
  `rating` INT NOT NULL DEFAULT 5,
  `message` VARCHAR(1000) NOT NULL,
  `avatar_url` VARCHAR(500) NULL DEFAULT NULL,
  `property_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `order` INT NOT NULL DEFAULT 0,
  `is_sample` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `testimonials_is_active_index` (`is_active`),
  KEY `testimonials_is_featured_index` (`is_featured`),
  KEY `testimonials_order_index` (`order`),
  CONSTRAINT `testimonials_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: partners
CREATE TABLE `partners` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `logo_url` VARCHAR(500) NOT NULL,
  `website_url` VARCHAR(500) NULL DEFAULT NULL,
  `category` VARCHAR(40) NOT NULL DEFAULT 'developer' COMMENT 'developer|bank|legal|interior|other',
  `order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `partners_is_active_index` (`is_active`),
  KEY `partners_order_index` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: jobOpenings
CREATE TABLE `job_openings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(75) NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `department` VARCHAR(120) NOT NULL,
  `location` VARCHAR(120) NOT NULL,
  `employment_type` VARCHAR(40) NOT NULL DEFAULT 'full-time' COMMENT 'full-time|part-time|contract|internship',
  `experience` VARCHAR(80) NULL DEFAULT NULL,
  `description` LONGTEXT NOT NULL,
  `responsibilities` JSON NULL,
  `requirements` JSON NULL,
  `salary_range` VARCHAR(80) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `posted_at` DATE NULL DEFAULT NULL,
  `closes_at` DATE NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_openings_slug_unique` (`slug`),
  KEY `job_openings_is_active_index` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: jobApplications
CREATE TABLE `job_applications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `resume_url` VARCHAR(500) NOT NULL,
  `cover_letter` TEXT NULL,
  `linkedin_url` VARCHAR(500) NULL DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'new' COMMENT 'new|shortlisted|interview|rejected|hired',
  `notes` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `job_applications_status_index` (`status`),
  CONSTRAINT `job_applications_job_id_foreign` FOREIGN KEY (`job_id`) REFERENCES `job_openings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: leads
CREATE TABLE `leads` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(191) NULL DEFAULT NULL,
  `message` TEXT NULL,
  `source` VARCHAR(40) NOT NULL DEFAULT 'contact-page' COMMENT 'property-enquiry|brochure-download|floor-plan-request|document-request|price-request|site-visit-request|callback-request|post-requirement|contact-page|home-loan|financial-assessment|bank-eligibility|legal-assistance|interior-design|sell-let|careers|partnership|flexible-workspace|direct-lease-retail|real-estate-awareness|newsletter|article|faq|locality-page|developer-page|whatsapp-click|call-click|hero-search|other',
  `property_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `article_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `page_slug` VARCHAR(120) NULL DEFAULT NULL,
  `page_url` VARCHAR(500) NULL DEFAULT NULL,
  `requirement` JSON NULL,
  `consent` TINYINT(1) NOT NULL DEFAULT 0,
  `utm` JSON NULL,
  `meta` JSON NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'new' COMMENT 'new|contacted|qualified|site-visit|negotiation|converted|lost',
  `priority` VARCHAR(40) NOT NULL DEFAULT 'medium' COMMENT 'low|medium|high',
  `assigned_to` BIGINT UNSIGNED NULL DEFAULT NULL,
  `follow_up_at` DATETIME NULL DEFAULT NULL,
  `lost_reason` VARCHAR(300) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL COMMENT 'soft delete',
  PRIMARY KEY (`id`),
  KEY `leads_assigned_to_index` (`assigned_to`),
  KEY `leads_status_index` (`status`),
  KEY `leads_priority_index` (`priority`),
  KEY `leads_source_index` (`source`),
  CONSTRAINT `leads_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL,
  CONSTRAINT `leads_article_id_foreign` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`) ON DELETE SET NULL,
  CONSTRAINT `leads_assigned_to_foreign` FOREIGN KEY (`assigned_to`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: leads — rows of leads.notes
CREATE TABLE `lead_notes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lead_id` BIGINT UNSIGNED NOT NULL,
  `text` TEXT NOT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_by_name` VARCHAR(80) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `lead_notes_lead_id_index` (`lead_id`),
  CONSTRAINT `lead_notes_lead_id_foreign` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_notes_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: leads — rows of leads.activities
CREATE TABLE `lead_activities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lead_id` BIGINT UNSIGNED NOT NULL,
  `type` VARCHAR(40) NOT NULL COMMENT 'created|status-changed|assigned|note-added|follow-up-set|contacted|email-sent|call-logged|priority-changed',
  `description` VARCHAR(300) NOT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `lead_activities_lead_id_index` (`lead_id`),
  CONSTRAINT `lead_activities_lead_id_foreign` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_activities_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: media
CREATE TABLE `media` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `public_id` VARCHAR(200) NULL DEFAULT NULL,
  `provider` VARCHAR(40) NOT NULL DEFAULT 'cloudinary' COMMENT 'cloudinary|external',
  `type` VARCHAR(40) NOT NULL DEFAULT 'image' COMMENT 'image|video|document',
  `width` INT NULL DEFAULT NULL,
  `height` INT NULL DEFAULT NULL,
  `bytes` INT NULL DEFAULT NULL,
  `format` VARCHAR(20) NULL DEFAULT NULL,
  `alt` VARCHAR(200) NOT NULL,
  `title` VARCHAR(200) NULL DEFAULT NULL,
  `folder` VARCHAR(120) NULL DEFAULT NULL,
  `tags` JSON NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `media_url_unique` (`url`),
  CONSTRAINT `media_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: redirects
CREATE TABLE `redirects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_path` VARCHAR(500) NOT NULL,
  `to_path` VARCHAR(500) NOT NULL,
  `status_code` VARCHAR(40) NOT NULL DEFAULT 301 COMMENT '301|302',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `note` VARCHAR(300) NULL DEFAULT NULL,
  `hits` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `redirects_is_active_index` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: newsletterSubscribers
CREATE TABLE `newsletter_subscribers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(191) NOT NULL,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `source` VARCHAR(40) NOT NULL DEFAULT 'newsletter' COMMENT 'property-enquiry|brochure-download|floor-plan-request|document-request|price-request|site-visit-request|callback-request|post-requirement|contact-page|home-loan|financial-assessment|bank-eligibility|legal-assistance|interior-design|sell-let|careers|partnership|flexible-workspace|direct-lease-retail|real-estate-awareness|newsletter|article|faq|locality-page|developer-page|whatsapp-click|call-click|hero-search|other',
  `status` VARCHAR(40) NOT NULL DEFAULT 'subscribed' COMMENT 'subscribed|unsubscribed',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `newsletter_subscribers_email_unique` (`email`),
  KEY `newsletter_subscribers_status_index` (`status`),
  KEY `newsletter_subscribers_source_index` (`source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: siteSettings
CREATE TABLE `site_settings` (
  `id` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'always 1 — one row per installation',
  `general` JSON NULL,
  `hero` JSON NULL,
  `navigation` JSON NULL,
  `social` JSON NULL,
  `footer` JSON NULL,
  `newsletter` JSON NULL,
  `integrations` JSON NULL,
  `leads` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: seoSettings
CREATE TABLE `seo_settings` (
  `id` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'always 1 — one row per installation',
  `site_url` JSON NOT NULL,
  `separator` JSON NULL,
  `title_templates` JSON NULL,
  `defaults` JSON NULL,
  `knowledge_graph` JSON NULL,
  `verification` JSON NULL,
  `robots_txt` JSON NULL,
  `llms_txt` JSON NULL,
  `sitemap` JSON NULL,
  `breadcrumbs` JSON NULL,
  `noindex` JSON NULL,
  `custom_head_html` JSON NULL,
  `custom_body_end_html` JSON NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: propertyViews
CREATE TABLE `property_views` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `viewed_at` DATETIME NOT NULL,
  `referrer` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `property_views_property_id_foreign` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- collection: apiTokens — Laravel Sanctum owns this table
CREATE TABLE `personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `token` VARCHAR(48) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `personal_access_tokens_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `admin_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
